// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: bird-food  |  Products: 29

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-188018",
    "tags": [
      "bird-food",
      "farm-animal",
      "chicken",
      "scratch-and-peck-feeds",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-538478",
    "tags": [
      "bird-food",
      "bird",
      "shop-by-bird",
      "cockatiel",
      "food",
      "vitakraft",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-233523",
    "tags": [
      "bird-food",
      "farm-animal",
      "chicken",
      "rooster-booster",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-216241",
    "tags": [
      "bird-food",
      "bird",
      "shop-by-bird",
      "wild-bird",
      "kaytee",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-100890",
    "tags": [
      "bird-food",
      "bird",
      "shop-by-bird",
      "parakeet",
      "food",
      "zupreem",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-538798",
    "tags": [
      "bird-food",
      "farm-animal",
      "chicken",
      "scratch-and-peck-feeds"
    ]
  },
  {
    "sku": "chewy-120",
    "tags": [
      "bird-food"
    ]
  },
  {
    "sku": "chewy-ginger",
    "tags": [
      "bird-food",
      "thyme",
      "colors-or-preservatives.,instock,,,,,,,,5d594294-2ce8-583d-b8ba-97117f39ad7f,03/05/2023-21:37:37"
    ]
  },
  {
    "sku": "chewy-244505",
    "tags": [
      "bird-food",
      "farm-animal",
      "chicken",
      "kent",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-366527",
    "tags": [
      "bird-food",
      "small-pet",
      "food",
      "suncoast-sugar-gliders",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "petsmart-5167132",
    "tags": [
      "bird-food",
      "bird",
      "food-and-treats",
      "pet-bird-food",
      "zupreem-nutblend-bird-food-3957-html",
      "zupreem"
    ]
  },
  {
    "sku": "petsmart-5271483",
    "tags": [
      "bird-food",
      "bird",
      "wild-bird-food-and-supplies",
      "wild-bird-food",
      "wagners"
    ]
  },
  {
    "sku": "petsmart-5159039",
    "tags": [
      "bird-food",
      "bird",
      "food-and-treats",
      "treats",
      "all-living-things"
    ]
  },
  {
    "sku": "petsmart-1041486",
    "tags": [
      "bird-food",
      "bird",
      "food-and-treats",
      "pet-bird-food",
      "lafeber's"
    ]
  },
  {
    "sku": "petsmart-5313425",
    "tags": [
      "bird-food",
      "bird",
      "food-and-treats",
      "treats",
      "all-living-things"
    ]
  },
  {
    "sku": "petsmart-5166955",
    "tags": [
      "bird-food",
      "bird",
      "food-and-treats",
      "pet-bird-food",
      "vitakraft"
    ]
  },
  {
    "sku": "petsmart-5271535",
    "tags": [
      "bird-food",
      "bird",
      "wild-bird-food-and-supplies",
      "wild-bird-food",
      "wagners"
    ]
  },
  {
    "sku": "amazon-pet-B0B5VZYDK4",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "bamc",
      "asin-B0B5VZYDK4"
    ]
  },
  {
    "sku": "amazon-pet-B01L6NSQW8",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "visit-the-petslife-store",
      "asin-B01L6NSQW8"
    ]
  },
  {
    "sku": "amazon-pet-B07V5BF6LD",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "pets",
      "asin-B07V5BF6LD"
    ]
  },
  {
    "sku": "amazon-pet-B079HVGB98",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "visit-the-jimmy-pet-products-store",
      "asin-B079HVGB98"
    ]
  },
  {
    "sku": "amazon-pet-B09LRPRB94",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "shanrya",
      "asin-B09LRPRB94"
    ]
  },
  {
    "sku": "amazon-pet-B0974RWXFK",
    "tags": [
      "bird-food",
      "pet-supplies",
      "small-animals",
      "health-supplies",
      "visit-the-refit-animal-care-store",
      "asin-B0974RWXFK"
    ]
  },
  {
    "sku": "amazon-pet-B08YX7FHY3",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "generic",
      "asin-B08YX7FHY3"
    ]
  },
  {
    "sku": "amazon-pet-B09W89B8G1",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "toys",
      "ufolet",
      "asin-B09W89B8G1"
    ]
  },
  {
    "sku": "amazon-pet-B07TD2QXZW",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "visit-the-petnest-store",
      "asin-B07TD2QXZW"
    ]
  },
  {
    "sku": "amazon-pet-B0B51KYL7K",
    "tags": [
      "bird-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B0B51KYL7K"
    ]
  },
  {
    "sku": "amazon-pet-B09QMGR6BX",
    "tags": [
      "bird-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B09QMGR6BX"
    ]
  },
  {
    "sku": "amazon-pet-B079CKFCZX",
    "tags": [
      "bird-food",
      "pet-supplies",
      "birds",
      "food",
      "visit-the-jainsons-pet-products-store",
      "asin-B079CKFCZX"
    ]
  }
];

export default entries;