// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: bird-toy  |  Products with image: 128 (3 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-109609",
    "tags": [
      "bird-toy",
      "bird",
      "feeders-waterers",
      "north-states"
    ]
  },
  {
    "sku": "chewy-331757",
    "tags": [
      "bird-toy",
      "bird",
      "shop-by-bird",
      "cockatiel",
      "toys-perches",
      "frisco"
    ]
  },
  {
    "sku": "petsmart-5273888",
    "tags": [
      "bird-toy",
      "bird",
      "toys-perches-and-decor",
      "toys",
      "a&amp;e"
    ]
  },
  {
    "sku": "petsmart-5269253",
    "tags": [
      "bird-toy",
      "bird",
      "toys-perches-and-decor",
      "toys",
      "all-living-things"
    ]
  },
  {
    "sku": "petsmart-5273876",
    "tags": [
      "bird-toy",
      "bird",
      "toys-perches-and-decor",
      "toys",
      "a&amp;e"
    ]
  },
  {
    "sku": "petsmart-5313591",
    "tags": [
      "bird-toy",
      "bird",
      "wild-bird-food-and-supplies",
      "outdoor-feeders",
      "rustic-farmhouse"
    ]
  },
  {
    "sku": "petsmart-5180314",
    "tags": [
      "bird-toy",
      "bird",
      "toys-perches-and-decor",
      "toys",
      "all-living-things"
    ]
  },
  {
    "sku": "petsmart-5249998",
    "tags": [
      "bird-toy",
      "bird",
      "cages-and-stands",
      "cages",
      "prevue-pet-products"
    ]
  },
  {
    "sku": "petsmart-5297827",
    "tags": [
      "bird-toy",
      "bird",
      "toys-perches-and-decor",
      "toys",
      "all-living-things"
    ]
  },
  {
    "sku": "amazon-pet-B01LMH18YQ",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "avianweb",
      "asin-B01LMH18YQ"
    ]
  },
  {
    "sku": "amazon-pet-B08JVLQS4P",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "backyard-barnyard",
      "asin-B08JVLQS4P"
    ]
  },
  {
    "sku": "amazon-pet-B002DZI4F8",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "prevue",
      "asin-B002DZI4F8"
    ]
  },
  {
    "sku": "amazon-pet-B09WD85VB3",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "visit-the-petnest-store",
      "asin-B09WD85VB3"
    ]
  },
  {
    "sku": "amazon-pet-B09KZJVZM8",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "topiky",
      "asin-B09KZJVZM8"
    ]
  },
  {
    "sku": "amazon-pet-B09HKYT44P",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "yuye",
      "asin-B09HKYT44P"
    ]
  },
  {
    "sku": "amazon-pet-B099WY96PR",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "pondicherry-pigeons",
      "asin-B099WY96PR"
    ]
  },
  {
    "sku": "amazon-pet-B09F6DL5QL",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "swings",
      "socialme",
      "asin-B09F6DL5QL"
    ]
  },
  {
    "sku": "amazon-pet-B0B191JX42",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-oxera-store",
      "asin-B0B191JX42"
    ]
  },
  {
    "sku": "amazon-pet-B094ZC8Y76",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "sumind",
      "asin-B094ZC8Y76"
    ]
  },
  {
    "sku": "amazon-pet-B07P6X9XKH",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-pets-empire-store",
      "asin-B07P6X9XKH"
    ]
  },
  {
    "sku": "amazon-pet-B0B58KLLQ3",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B58KLLQ3"
    ]
  },
  {
    "sku": "amazon-pet-B09RXPSH66",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "food",
      "01-02-015",
      "asin-B09RXPSH66"
    ]
  },
  {
    "sku": "amazon-pet-B0B4S31FGF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "maxbell",
      "asin-B0B4S31FGF"
    ]
  },
  {
    "sku": "amazon-pet-B0B1D3KTVP",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "food",
      "generic",
      "asin-B0B1D3KTVP"
    ]
  },
  {
    "sku": "amazon-pet-B09ZJ4Z4F2",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "calandis",
      "asin-B09ZJ4Z4F2"
    ]
  },
  {
    "sku": "amazon-pet-B0B296BXXK",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "small-animals",
      "health-supplies",
      "generic",
      "asin-B0B296BXXK"
    ]
  },
  {
    "sku": "amazon-pet-B0B4S7YJJH",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "generic",
      "asin-B0B4S7YJJH"
    ]
  },
  {
    "sku": "amazon-pet-B09DL7XK6J",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "visit-the-arythe-store",
      "asin-B09DL7XK6J"
    ]
  },
  {
    "sku": "amazon-pet-B07WD8LHLX",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "keersi",
      "asin-B07WD8LHLX"
    ]
  },
  {
    "sku": "amazon-pet-B098PLRCCX",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "wuqioei",
      "asin-B098PLRCCX"
    ]
  },
  {
    "sku": "amazon-pet-B07Q1X3NW7",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "finyii",
      "asin-B07Q1X3NW7"
    ]
  },
  {
    "sku": "amazon-pet-B0B2966QNT",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "small-animals",
      "health-supplies",
      "generic",
      "asin-B0B2966QNT"
    ]
  },
  {
    "sku": "amazon-pet-B0B39FB7KY",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "generic",
      "asin-B0B39FB7KY"
    ]
  },
  {
    "sku": "amazon-pet-B09Y2BBXH9",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "trendy-retail",
      "asin-B09Y2BBXH9"
    ]
  },
  {
    "sku": "amazon-pet-B09884TBS8",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "hui",
      "asin-B09884TBS8"
    ]
  },
  {
    "sku": "amazon-pet-B0B39HYZ19",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B39HYZ19"
    ]
  },
  {
    "sku": "amazon-pet-B09GNRNYFH",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "trendy-retail",
      "asin-B09GNRNYFH"
    ]
  },
  {
    "sku": "amazon-pet-B0B58J6BH7",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B58J6BH7"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8YD392",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B09Y8YD392"
    ]
  },
  {
    "sku": "amazon-pet-B0B2RRBYTF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "generic",
      "asin-B0B2RRBYTF"
    ]
  },
  {
    "sku": "amazon-pet-B07Y9L8D96",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "yuniror",
      "asin-B07Y9L8D96"
    ]
  },
  {
    "sku": "amazon-pet-B09B8M3C1B",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "sojare",
      "asin-B09B8M3C1B"
    ]
  },
  {
    "sku": "amazon-pet-B0B2ZDJJBZ",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "food",
      "cryfokt",
      "asin-B0B2ZDJJBZ"
    ]
  },
  {
    "sku": "amazon-pet-B079S2FLYK",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "visit-the-sage-square-store",
      "asin-B079S2FLYK"
    ]
  },
  {
    "sku": "amazon-pet-B06X6GSTCX",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-pets-empire-store",
      "asin-B06X6GSTCX"
    ]
  },
  {
    "sku": "amazon-pet-B000OB0ODS",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "super-bird",
      "asin-B000OB0ODS"
    ]
  },
  {
    "sku": "amazon-pet-B0827V38ZN",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "health-supplies",
      "visit-the-boltz-store",
      "asin-B0827V38ZN"
    ]
  },
  {
    "sku": "amazon-pet-B095CR8MJL",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "ladders",
      "crisis",
      "asin-B095CR8MJL"
    ]
  },
  {
    "sku": "amazon-pet-B0B292LTC8",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B292LTC8"
    ]
  },
  {
    "sku": "amazon-pet-B09HR8RYZR",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "generic",
      "asin-B09HR8RYZR"
    ]
  },
  {
    "sku": "amazon-pet-B08JPT6HT4",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "aiterwu",
      "asin-B08JPT6HT4"
    ]
  },
  {
    "sku": "amazon-pet-B071F1FN2Z",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "visit-the-pets-empire-store",
      "asin-B071F1FN2Z"
    ]
  },
  {
    "sku": "amazon-pet-B09WMZFTYX",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "meiyya",
      "asin-B09WMZFTYX"
    ]
  },
  {
    "sku": "amazon-pet-B09JSPWTHR",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "lelepet",
      "asin-B09JSPWTHR"
    ]
  },
  {
    "sku": "amazon-pet-B08MC2TQJ1",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "nature-care",
      "asin-B08MC2TQJ1"
    ]
  },
  {
    "sku": "amazon-pet-B09YYZMQJV",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "velaurs",
      "asin-B09YYZMQJV"
    ]
  },
  {
    "sku": "amazon-pet-B09Y2TVX2X",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "houh",
      "asin-B09Y2TVX2X"
    ]
  },
  {
    "sku": "amazon-pet-B08TTH85YP",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcages",
      "visit-the-central-fish-aquarium-store",
      "asin-B08TTH85YP"
    ]
  },
  {
    "sku": "amazon-pet-B0B1DB5CK5",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B1DB5CK5"
    ]
  },
  {
    "sku": "amazon-pet-B09K6P83CY",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "conodia",
      "asin-B09K6P83CY"
    ]
  },
  {
    "sku": "amazon-pet-B09P6PXPWC",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "hoseten",
      "asin-B09P6PXPWC"
    ]
  },
  {
    "sku": "amazon-pet-B09PZ27NYH",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "ouee",
      "asin-B09PZ27NYH"
    ]
  },
  {
    "sku": "amazon-pet-B08M3TKGPF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "small-animals",
      "health-supplies",
      "wuqioei",
      "asin-B08M3TKGPF"
    ]
  },
  {
    "sku": "amazon-pet-B087YXQDRL",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-sage-square-store",
      "asin-B087YXQDRL"
    ]
  },
  {
    "sku": "amazon-pet-B09YWT73YW",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "wnuv",
      "asin-B09YWT73YW"
    ]
  },
  {
    "sku": "amazon-pet-B07TH9GGNB",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "backtonest",
      "asin-B07TH9GGNB"
    ]
  },
  {
    "sku": "amazon-pet-B09B2RL154",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "ouee",
      "asin-B09B2RL154"
    ]
  },
  {
    "sku": "amazon-pet-B09ZKWZYC9",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcages",
      "kapoor-enterprise",
      "asin-B09ZKWZYC9"
    ]
  },
  {
    "sku": "amazon-pet-B09ZKZDJF6",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "vms-india",
      "asin-B09ZKZDJF6"
    ]
  },
  {
    "sku": "amazon-pet-B09GPK6FZ9",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "skybeings",
      "asin-B09GPK6FZ9"
    ]
  },
  {
    "sku": "amazon-pet-B09NMBN6LT",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "yuniror",
      "asin-B09NMBN6LT"
    ]
  },
  {
    "sku": "amazon-pet-B09CMZPKCY",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "visit-the-psm-heaven-in-home-store",
      "asin-B09CMZPKCY"
    ]
  },
  {
    "sku": "amazon-pet-B09PBYSPYD",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B09PBYSPYD"
    ]
  },
  {
    "sku": "amazon-pet-B0B1RVZ9FK",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "velaurs",
      "asin-B0B1RVZ9FK"
    ]
  },
  {
    "sku": "amazon-pet-B099SCSBVZ",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "sutinna",
      "asin-B099SCSBVZ"
    ]
  },
  {
    "sku": "amazon-pet-B0B5HFKM7D",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "excluzo",
      "asin-B0B5HFKM7D"
    ]
  },
  {
    "sku": "amazon-pet-B09ZB6FMC6",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B09ZB6FMC6"
    ]
  },
  {
    "sku": "amazon-pet-B0B1932W6T",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "generic",
      "asin-B0B1932W6T"
    ]
  },
  {
    "sku": "amazon-pet-B092P48RWN",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "jingyig",
      "asin-B092P48RWN"
    ]
  },
  {
    "sku": "amazon-pet-B09DKNHN5R",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-thor-store",
      "asin-B09DKNHN5R"
    ]
  },
  {
    "sku": "amazon-pet-B001CU3GDU",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "living-world",
      "asin-B001CU3GDU"
    ]
  },
  {
    "sku": "amazon-pet-B0B1J8J8JT",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "generic",
      "asin-B0B1J8J8JT"
    ]
  },
  {
    "sku": "amazon-pet-B08MVR8Z93",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "denkerm",
      "asin-B08MVR8Z93"
    ]
  },
  {
    "sku": "amazon-pet-B074WNXJTV",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "jusney",
      "asin-B074WNXJTV"
    ]
  },
  {
    "sku": "amazon-pet-B0B5HFPMLT",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "excluzo",
      "asin-B0B5HFPMLT"
    ]
  },
  {
    "sku": "amazon-pet-B087X6BDCK",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-western-era-store",
      "asin-B087X6BDCK"
    ]
  },
  {
    "sku": "amazon-pet-B0B58JDB59",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B58JDB59"
    ]
  },
  {
    "sku": "amazon-pet-B0B4S8HQYW",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "beds",
      "generic",
      "asin-B0B4S8HQYW"
    ]
  },
  {
    "sku": "amazon-pet-B09LYVVC1W",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "food",
      "socialme",
      "asin-B09LYVVC1W"
    ]
  },
  {
    "sku": "amazon-pet-B09KZR8962",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "swings",
      "topiky",
      "asin-B09KZR8962"
    ]
  },
  {
    "sku": "amazon-pet-B09JP4TJT6",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "luroze",
      "asin-B09JP4TJT6"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8YD8PL",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "swings",
      "generic",
      "asin-B09Y8YD8PL"
    ]
  },
  {
    "sku": "amazon-pet-B0B58JRM7K",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B58JRM7K"
    ]
  },
  {
    "sku": "amazon-pet-B00Q1U4IWY",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "benelux",
      "asin-B00Q1U4IWY"
    ]
  },
  {
    "sku": "amazon-pet-B08S3VHTHQ",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-jainsons-pet-products-store",
      "asin-B08S3VHTHQ"
    ]
  },
  {
    "sku": "amazon-pet-B09HKXKJDN",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "food",
      "generic",
      "asin-B09HKXKJDN"
    ]
  },
  {
    "sku": "amazon-pet-B09WDV15GF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "visit-the-sadhubela-store",
      "asin-B09WDV15GF"
    ]
  },
  {
    "sku": "amazon-pet-B07527N37S",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcages",
      "birds'-park",
      "asin-B07527N37S"
    ]
  },
  {
    "sku": "amazon-pet-B0B6W7WHLF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "ladders",
      "generic",
      "asin-B0B6W7WHLF"
    ]
  },
  {
    "sku": "amazon-pet-B0B582CZVT",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B582CZVT"
    ]
  },
  {
    "sku": "amazon-pet-B09XHXBFMB",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "generic",
      "asin-B09XHXBFMB"
    ]
  },
  {
    "sku": "amazon-pet-B0108L2FWG",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-ksk-store",
      "asin-B0108L2FWG"
    ]
  },
  {
    "sku": "amazon-pet-B0B4D356NY",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "promote",
      "asin-B0B4D356NY"
    ]
  },
  {
    "sku": "amazon-pet-B09KZM5VJ4",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "shanrya",
      "asin-B09KZM5VJ4"
    ]
  },
  {
    "sku": "amazon-pet-B095X9JGWR",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "dimu",
      "asin-B095X9JGWR"
    ]
  },
  {
    "sku": "amazon-pet-B0B6ZVJSW5",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "maxbell",
      "asin-B0B6ZVJSW5"
    ]
  },
  {
    "sku": "amazon-pet-B07Q4V4L79",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "heepdd",
      "asin-B07Q4V4L79"
    ]
  },
  {
    "sku": "amazon-pet-B09Z26NJYL",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "zhatendmo",
      "asin-B09Z26NJYL"
    ]
  },
  {
    "sku": "amazon-pet-B0B5GGMG16",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "visit-the-sparrow-daughter-store",
      "asin-B0B5GGMG16"
    ]
  },
  {
    "sku": "amazon-pet-B099WM3TZW",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcages",
      "kapoor-pets",
      "asin-B099WM3TZW"
    ]
  },
  {
    "sku": "amazon-pet-B08VHXRGJB",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "rypet",
      "asin-B08VHXRGJB"
    ]
  },
  {
    "sku": "amazon-pet-B09RB9MS7D",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "shanrya",
      "asin-B09RB9MS7D"
    ]
  },
  {
    "sku": "amazon-pet-B09S3QF66S",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "hoseten",
      "asin-B09S3QF66S"
    ]
  },
  {
    "sku": "amazon-pet-B0B1D9NFP4",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B1D9NFP4"
    ]
  },
  {
    "sku": "amazon-pet-B088674JZF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "visit-the-sage-square-store",
      "asin-B088674JZF"
    ]
  },
  {
    "sku": "amazon-pet-B09GPHVKYV",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "skybeings",
      "asin-B09GPHVKYV"
    ]
  },
  {
    "sku": "amazon-pet-B0B42LYNSR",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "generic",
      "asin-B0B42LYNSR"
    ]
  },
  {
    "sku": "amazon-pet-B0B5HL2RFF",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "health-supplies",
      "visit-the-petlife-store",
      "asin-B0B5HL2RFF"
    ]
  },
  {
    "sku": "amazon-pet-B09ZRMT1JG",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "bizofft",
      "asin-B09ZRMT1JG"
    ]
  },
  {
    "sku": "amazon-pet-B0B46FVK6P",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "generic",
      "asin-B0B46FVK6P"
    ]
  },
  {
    "sku": "amazon-pet-B0B3JKYT75",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B3JKYT75"
    ]
  },
  {
    "sku": "amazon-pet-B08D96TYCB",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "josopa",
      "asin-B08D96TYCB"
    ]
  },
  {
    "sku": "amazon-pet-B0B14P9SRD",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B14P9SRD"
    ]
  },
  {
    "sku": "amazon-pet-B0875VG4FC",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "visit-the-sage-square-store",
      "asin-B0875VG4FC"
    ]
  },
  {
    "sku": "amazon-pet-B091YRN6KB",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "generic",
      "asin-B091YRN6KB"
    ]
  },
  {
    "sku": "amazon-pet-B01HO0J676",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "birdcages",
      "yml",
      "asin-B01HO0J676"
    ]
  },
  {
    "sku": "amazon-pet-B099J9LXF2",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "layfuz",
      "asin-B099J9LXF2"
    ]
  },
  {
    "sku": "amazon-pet-B0B1TBNPFB",
    "tags": [
      "bird-toy",
      "pet-supplies",
      "birds",
      "toys",
      "visit-the-sage-square-store",
      "asin-B0B1TBNPFB"
    ]
  }
];

export default entries;