// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: bird-accessory  |  Products: 25

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-bright teeth and healthy gums. The proprietary formula is designed to dissolve the protein pellicle to which plaque",
    "tags": [
      "bird-accessory",
      "and-you-re-done-plus",
      "'https://image.chewy.com/is/image/catalog/693110_pt3._ac_ss500_v1669125654_.jpg'"
    ]
  },
  {
    "sku": "chewy-Lentils",
    "tags": [
      "bird-accessory"
    ]
  },
  {
    "sku": "petsmart-5284997",
    "tags": [
      "bird-accessory",
      "bird",
      "grooming",
      "nail-and-beak-trimmers",
      "all-living-things"
    ]
  },
  {
    "sku": "amazon-pet-B07JQG5FD2",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "health-supplies",
      "pet-care-international",
      "asin-B07JQG5FD2"
    ]
  },
  {
    "sku": "amazon-pet-B09KXKKHC6",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "toys",
      "wumuge",
      "asin-B09KXKKHC6"
    ]
  },
  {
    "sku": "amazon-pet-B09KZB9LXW",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "hoseten",
      "asin-B09KZB9LXW"
    ]
  },
  {
    "sku": "amazon-pet-B09NMBKVVD",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "bird-diapers",
      "gind",
      "asin-B09NMBKVVD"
    ]
  },
  {
    "sku": "amazon-pet-B0002AXGPE",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "toys",
      "prevue-hendryx",
      "asin-B0002AXGPE"
    ]
  },
  {
    "sku": "amazon-pet-B0B39H5ZJ4",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B39H5ZJ4"
    ]
  },
  {
    "sku": "amazon-pet-B08RWP37ZZ",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B08RWP37ZZ"
    ]
  },
  {
    "sku": "amazon-pet-B09YVX1ML7",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "01-02-015",
      "asin-B09YVX1ML7"
    ]
  },
  {
    "sku": "amazon-pet-B08BKXC83R",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "health-supplies",
      "tand",
      "asin-B08BKXC83R"
    ]
  },
  {
    "sku": "amazon-pet-B09TKJFYSZ",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "nests",
      "tnz-creations",
      "asin-B09TKJFYSZ"
    ]
  },
  {
    "sku": "amazon-pet-B0B1D8Z4FQ",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "toys",
      "generic",
      "asin-B0B1D8Z4FQ"
    ]
  },
  {
    "sku": "amazon-pet-B09J1DR9H1",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "swings",
      "pondicherry-pigeons",
      "asin-B09J1DR9H1"
    ]
  },
  {
    "sku": "amazon-pet-B07JYS3892",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "health-supplies",
      "pet-care-international",
      "asin-B07JYS3892"
    ]
  },
  {
    "sku": "amazon-pet-B09GRN55CD",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "trendy-retail",
      "asin-B09GRN55CD"
    ]
  },
  {
    "sku": "amazon-pet-B0B1LF97ZM",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "fasj",
      "asin-B0B1LF97ZM"
    ]
  },
  {
    "sku": "amazon-pet-B098BLT8FM",
    "tags": [
      "bird-accessory",
      "pet-supplies",
      "birds",
      "toys",
      "super-cluck-co.",
      "asin-B098BLT8FM"
    ]
  },
  {
    "sku": "aliexpress-pet-00251",
    "tags": [
      "bird-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00966",
    "tags": [
      "bird-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01192",
    "tags": [
      "bird-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01206",
    "tags": [
      "bird-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01471",
    "tags": [
      "bird-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01505",
    "tags": [
      "bird-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  }
];

export default entries;