// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-wet-food  |  Products with image: 28 (5 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-102305",
    "tags": [
      "cat-wet-food",
      "cat",
      "food",
      "wet-food",
      "purina-pro-plan",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-342183",
    "tags": [
      "cat-wet-food",
      "cat",
      "food",
      "wet-food",
      "optimeal",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-263633",
    "tags": [
      "cat-wet-food",
      "cat",
      "treats",
      "trial-size-treats",
      "the-new-zealand-natural-pet-food-co.",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-147768",
    "tags": [
      "cat-wet-food",
      "cat",
      "food",
      "wet-food",
      "variety-packs",
      "tiny-tiger",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "petsmart-5322182",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "made-by-nacho"
    ]
  },
  {
    "sku": "petsmart-1021242",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5310577",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "fancy-feast"
    ]
  },
  {
    "sku": "petsmart-5282141",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "friskies"
    ]
  },
  {
    "sku": "petsmart-5230668",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "purina-pro-plan"
    ]
  },
  {
    "sku": "petsmart-5279756",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "instinct"
    ]
  },
  {
    "sku": "petsmart-5246504",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5200244",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "purina-pro-plan"
    ]
  },
  {
    "sku": "petsmart-5178643",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "wellness"
    ]
  },
  {
    "sku": "petsmart-5231496",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "food-toppers",
      "fancy-feast"
    ]
  },
  {
    "sku": "petsmart-5299097",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "purina-pro-plan"
    ]
  },
  {
    "sku": "petsmart-5309174",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "food-toppers",
      "nulo"
    ]
  },
  {
    "sku": "petsmart-5268798",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "food-toppers",
      "nulo"
    ]
  },
  {
    "sku": "petsmart-5164704",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "fancy-feast"
    ]
  },
  {
    "sku": "petsmart-5200143",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5281443",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "solid-gold"
    ]
  },
  {
    "sku": "petsmart-5164052",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "fancy-feast"
    ]
  },
  {
    "sku": "petsmart-5268799",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "food-toppers",
      "nulo"
    ]
  },
  {
    "sku": "petsmart-5266917",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "purina-pro-plan"
    ]
  },
  {
    "sku": "petsmart-5280554",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "wet-food",
      "wellness"
    ]
  },
  {
    "sku": "petsmart-5221049",
    "tags": [
      "cat-wet-food",
      "cat",
      "food-and-treats",
      "food-toppers",
      "fancy-feast"
    ]
  },
  {
    "sku": "amazon-pet-B09NW9YRNQ",
    "tags": [
      "cat-wet-food",
      "pet-supplies",
      "cats",
      "food",
      "wet",
      "fancy-feast",
      "asin-B09NW9YRNQ"
    ]
  },
  {
    "sku": "amazon-pet-B09QX873H7",
    "tags": [
      "cat-wet-food",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "visit-the-pets-empire-store",
      "asin-B09QX873H7"
    ]
  },
  {
    "sku": "amazon-pet-B0B42MX729",
    "tags": [
      "cat-wet-food",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter",
      "generic",
      "asin-B0B42MX729"
    ]
  }
];

export default entries;