// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-toy  |  Products: 240

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-201261",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "plush-mice-toys",
      "hartz"
    ]
  },
  {
    "sku": "chewy-108561",
    "tags": [
      "cat-toy",
      "cat",
      "trees-condos-scratchers",
      "window-perches",
      "kitty-cot"
    ]
  },
  {
    "sku": "chewy-233307",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "balls-chasers",
      "frisco"
    ]
  },
  {
    "sku": "chewy-190715",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "plush-mice-toys",
      "catstages"
    ]
  },
  {
    "sku": "chewy-254177",
    "tags": [
      "cat-toy",
      "cat",
      "trees-condos-scratchers",
      "wall-shelves",
      "myzoo"
    ]
  },
  {
    "sku": "chewy-216950",
    "tags": [
      "cat-toy",
      "cat",
      "trees-condos-scratchers",
      "trees-condos",
      "medium-31-59",
      "go-pet-club"
    ]
  },
  {
    "sku": "petsmart-5288496",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "teasers",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5288005",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "balls-and-chasers",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5305878",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "catnip",
      "mad-cat"
    ]
  },
  {
    "sku": "petsmart-5287530",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "plush-toys",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5324010",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "balls-and-chasers",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5264295",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "electronic-and-interactive",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5305962",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "electronic-and-interactive",
      "petlinks"
    ]
  },
  {
    "sku": "amazon-pet-B0796LTTT6",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "retractable",
      "asin-B0796LTTT6"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8XPVSW",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "generic",
      "asin-B09Y8XPVSW"
    ]
  },
  {
    "sku": "amazon-pet-B0B42N1SL1",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "generic",
      "asin-B0B42N1SL1"
    ]
  },
  {
    "sku": "amazon-pet-B08DV11VYH",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "poochbox",
      "asin-B08DV11VYH"
    ]
  },
  {
    "sku": "amazon-pet-B09KQQ94PY",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-rvpaws-store",
      "asin-B09KQQ94PY"
    ]
  },
  {
    "sku": "amazon-pet-B0B58K76WV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "generic",
      "asin-B0B58K76WV"
    ]
  },
  {
    "sku": "amazon-pet-B08Z8GXQP2",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-psk-pet-mart-store",
      "asin-B08Z8GXQP2"
    ]
  },
  {
    "sku": "amazon-pet-B0915KMWHV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "generic",
      "asin-B0915KMWHV"
    ]
  },
  {
    "sku": "amazon-pet-B099NP5DRP",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "mugasty",
      "asin-B099NP5DRP"
    ]
  },
  {
    "sku": "amazon-pet-B09DB1MCW1",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "01",
      "asin-B09DB1MCW1"
    ]
  },
  {
    "sku": "amazon-pet-B09J281BNP",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-rvpaws-store",
      "asin-B09J281BNP"
    ]
  },
  {
    "sku": "amazon-pet-B07RYPRTD2",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "petlinks",
      "asin-B07RYPRTD2"
    ]
  },
  {
    "sku": "amazon-pet-B097PKTQRB",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratcher-accessories-parts",
      "dd-enterprises",
      "asin-B097PKTQRB"
    ]
  },
  {
    "sku": "amazon-pet-B08M3KYHGC",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-psk-pet-mart-store",
      "asin-B08M3KYHGC"
    ]
  },
  {
    "sku": "amazon-pet-B0B292CGTV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "treats",
      "snacks",
      "petstages",
      "asin-B0B292CGTV"
    ]
  },
  {
    "sku": "amazon-pet-B0B2P27N2C",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "generic",
      "asin-B0B2P27N2C"
    ]
  },
  {
    "sku": "amazon-pet-B09C6BWJTK",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "tand",
      "asin-B09C6BWJTK"
    ]
  },
  {
    "sku": "amazon-pet-B0B1J9T1Y4",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-scoops",
      "generic",
      "asin-B0B1J9T1Y4"
    ]
  },
  {
    "sku": "amazon-pet-B0B2938VJD",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "beds",
      "generic",
      "asin-B0B2938VJD"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8XRNXK",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "generic",
      "asin-B09Y8XRNXK"
    ]
  },
  {
    "sku": "amazon-pet-B08K4Q1HJ5",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "partykindom",
      "asin-B08K4Q1HJ5"
    ]
  },
  {
    "sku": "amazon-pet-B09ZB5NYCV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "mice-animal-toys",
      "generic",
      "asin-B09ZB5NYCV"
    ]
  },
  {
    "sku": "amazon-pet-B0B42N52TV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "generic",
      "asin-B0B42N52TV"
    ]
  },
  {
    "sku": "amazon-pet-B09BMSFL5F",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "filr",
      "asin-B09BMSFL5F"
    ]
  },
  {
    "sku": "aliexpress-pet-00004",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00014",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00044",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00048",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00051",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00055",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00058",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00061",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00075",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00078",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00082",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00089",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00095",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00121",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00122",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00128",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00129",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00133",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00165",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00171",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00213",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00223",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00239",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00247",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00283",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00286",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00287",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00309",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00314",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00347",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00355",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00364",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00367",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00370",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00373",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00375",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00400",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00405",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00409",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00430",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00435",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00444",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00446",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00447",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00455",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00462",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00465",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00471",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00472",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00473",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00487",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00490",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00499",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00502",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00511",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00512",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00513",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00514",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00522",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00528",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00539",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00542",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00543",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00545",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00574",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00586",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00617",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00637",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00648",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00653",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00664",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00665",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00668",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00670",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00672",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00676",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00678",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00682",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00690",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00696",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00697",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00700",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00707",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00708",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00711",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00726",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00744",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00816",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00824",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00852",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00871",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00877",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00883",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00884",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00887",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00890",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00892",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00893",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00900",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00901",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00903",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00905",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00907",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00908",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00913",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00919",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00922",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00935",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00957",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00961",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00963",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00979",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00984",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00994",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00998",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01003",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01007",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01011",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01012",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01015",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-01024",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01033",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01045",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01050",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01059",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01066",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01069",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01071",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01088",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01090",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01106",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01113",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01115",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01118",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01132",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01145",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01161",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-01198",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01199",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01202",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01203",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01205",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01215",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01245",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01247",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01266",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01270",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01274",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01276",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01296",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01297",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01310",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01314",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01331",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01345",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01346",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01351",
    "tags": [
      "cat-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-01354",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01355",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01358",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01393",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01417",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01432",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01433",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01434",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01439",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01452",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01457",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01473",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01477",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01479",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01532",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01539",
    "tags": [
      "cat-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01542",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01558",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01563",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01588",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01593",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01620",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01645",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01670",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01702",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01708",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01718",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01738",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01749",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01754",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01764",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01768",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01777",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01803",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01813",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01816",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01820",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01845",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01865",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01929",
    "tags": [
      "cat-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01936",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01948",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01951",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01972",
    "tags": [
      "cat-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01980",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01984",
    "tags": [
      "cat-toy",
      "popular",
      "in-stock"
    ]
  }
];

export default entries;