// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-toy  |  Products with image: 32 (5 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-108561",
    "tags": [
      "cat-toy",
      "cat",
      "trees-condos-scratchers",
      "window-perches",
      "kitty-cot"
    ]
  },
  {
    "sku": "chewy-254177",
    "tags": [
      "cat-toy",
      "cat",
      "trees-condos-scratchers",
      "wall-shelves",
      "myzoo"
    ]
  },
  {
    "sku": "petsmart-5288496",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "teasers",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5288005",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "balls-and-chasers",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5305878",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "catnip",
      "mad-cat"
    ]
  },
  {
    "sku": "petsmart-5287530",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "plush-toys",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5264295",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "electronic-and-interactive",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5305962",
    "tags": [
      "cat-toy",
      "cat",
      "toys",
      "electronic-and-interactive",
      "petlinks"
    ]
  },
  {
    "sku": "amazon-pet-B0796LTTT6",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "retractable",
      "asin-B0796LTTT6"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8XPVSW",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "generic",
      "asin-B09Y8XPVSW"
    ]
  },
  {
    "sku": "amazon-pet-B0B42N1SL1",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "generic",
      "asin-B0B42N1SL1"
    ]
  },
  {
    "sku": "amazon-pet-B08DV11VYH",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "poochbox",
      "asin-B08DV11VYH"
    ]
  },
  {
    "sku": "amazon-pet-B09KQQ94PY",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-rvpaws-store",
      "asin-B09KQQ94PY"
    ]
  },
  {
    "sku": "amazon-pet-B0B58K76WV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "generic",
      "asin-B0B58K76WV"
    ]
  },
  {
    "sku": "amazon-pet-B08Z8GXQP2",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-psk-pet-mart-store",
      "asin-B08Z8GXQP2"
    ]
  },
  {
    "sku": "amazon-pet-B0915KMWHV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "generic",
      "asin-B0915KMWHV"
    ]
  },
  {
    "sku": "amazon-pet-B099NP5DRP",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "mugasty",
      "asin-B099NP5DRP"
    ]
  },
  {
    "sku": "amazon-pet-B09DB1MCW1",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "01",
      "asin-B09DB1MCW1"
    ]
  },
  {
    "sku": "amazon-pet-B09J281BNP",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-rvpaws-store",
      "asin-B09J281BNP"
    ]
  },
  {
    "sku": "amazon-pet-B07RYPRTD2",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "petlinks",
      "asin-B07RYPRTD2"
    ]
  },
  {
    "sku": "amazon-pet-B097PKTQRB",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratcher-accessories-parts",
      "dd-enterprises",
      "asin-B097PKTQRB"
    ]
  },
  {
    "sku": "amazon-pet-B08M3KYHGC",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "visit-the-psk-pet-mart-store",
      "asin-B08M3KYHGC"
    ]
  },
  {
    "sku": "amazon-pet-B0B292CGTV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "treats",
      "snacks",
      "petstages",
      "asin-B0B292CGTV"
    ]
  },
  {
    "sku": "amazon-pet-B0B2P27N2C",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "generic",
      "asin-B0B2P27N2C"
    ]
  },
  {
    "sku": "amazon-pet-B09C6BWJTK",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "tand",
      "asin-B09C6BWJTK"
    ]
  },
  {
    "sku": "amazon-pet-B0B1J9T1Y4",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-scoops",
      "generic",
      "asin-B0B1J9T1Y4"
    ]
  },
  {
    "sku": "amazon-pet-B0B2938VJD",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "beds",
      "generic",
      "asin-B0B2938VJD"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8XRNXK",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "generic",
      "asin-B09Y8XRNXK"
    ]
  },
  {
    "sku": "amazon-pet-B08K4Q1HJ5",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "partykindom",
      "asin-B08K4Q1HJ5"
    ]
  },
  {
    "sku": "amazon-pet-B09ZB5NYCV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "mice-animal-toys",
      "generic",
      "asin-B09ZB5NYCV"
    ]
  },
  {
    "sku": "amazon-pet-B0B42N52TV",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "generic",
      "asin-B0B42N52TV"
    ]
  },
  {
    "sku": "amazon-pet-B09BMSFL5F",
    "tags": [
      "cat-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "filr",
      "asin-B09BMSFL5F"
    ]
  }
];

export default entries;