// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-accessory  |  Products: 172

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-314471",
    "tags": [
      "cat-accessory",
      "pet-parents",
      "personalized-gifts",
      "coffee-mugs-tumblers",
      "904-custom"
    ]
  },
  {
    "sku": "chewy-93547",
    "tags": [
      "cat-accessory",
      "cat",
      "treats",
      "soft-chewy-treats",
      "tomlyn",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-64596",
    "tags": [
      "cat-accessory",
      "cat",
      "crates-pens-gates",
      "gates",
      "mypet"
    ]
  },
  {
    "sku": "chewy-145316",
    "tags": [
      "cat-accessory",
      "cat",
      "trees-condos-scratchers",
      "trees-condos",
      "medium-31-59",
      "on2pets"
    ]
  },
  {
    "sku": "chewy-75286",
    "tags": [
      "cat-accessory",
      "cat",
      "crates-pens-gates",
      "doors",
      "cat-mate"
    ]
  },
  {
    "sku": "chewy-this litter traps and eliminates odor without harmful perfumes. Its lightweight design makes it easy to scoop and pour—plus",
    "tags": [
      "cat-accessory",
      "urinary-stones-or-blood-in-the-urine.-it-is-paw-fect-for-single-or-multicat-households.,instock,['https://image.chewy.com/is/image/catalog/683318_main._ac_ss500_v1666126221_.jpg'",
      "has-ingredients",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-153158",
    "tags": [
      "cat-accessory",
      "cat",
      "leashes-collars-harnesses",
      "collars",
      "frisco"
    ]
  },
  {
    "sku": "chewy-186097",
    "tags": [
      "cat-accessory",
      "cat",
      "bowls-feeders",
      "bowls-dishes",
      "petrageous-designs"
    ]
  },
  {
    "sku": "petsmart-5192165",
    "tags": [
      "cat-accessory",
      "cat",
      "bowls-and-feeders",
      "placemats",
      "drymate"
    ]
  },
  {
    "sku": "petsmart-5172481",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "covered-beds",
      "kandh-clubhouse-cat-bed-5572-html",
      "k&amp;h"
    ]
  },
  {
    "sku": "petsmart-5181514",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "furniture-and-towers",
      "trixie-moriles-cat-tree-17213-html",
      "trixie"
    ]
  },
  {
    "sku": "petsmart-5305316",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "furniture-and-towers",
      "armarkat"
    ]
  },
  {
    "sku": "petsmart-5266568",
    "tags": [
      "cat-accessory",
      "cat",
      "cleaning-and-repellents",
      "stain-and-odor-removers",
      "nature's-miracle"
    ]
  },
  {
    "sku": "petsmart-5180865",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "furniture-and-towers",
      "armarkat"
    ]
  },
  {
    "sku": "petsmart-5305226",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "covered-beds",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5149449",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "heated-beds",
      "k&amp;h"
    ]
  },
  {
    "sku": "petsmart-5312631",
    "tags": [
      "cat-accessory",
      "cat",
      "collars-harnesses-and-leashes",
      "collars",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5265493",
    "tags": [
      "cat-accessory",
      "cat",
      "collars-harnesses-and-leashes",
      "collars",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5333552",
    "tags": [
      "cat-accessory",
      "cat",
      "collars-harnesses-and-leashes",
      "collars",
      "made-by-cleo"
    ]
  },
  {
    "sku": "petsmart-5268776",
    "tags": [
      "cat-accessory",
      "cat",
      "cleaning-and-repellents",
      "stain-and-odor-removers",
      "nature's-miracle"
    ]
  },
  {
    "sku": "petsmart-5124258",
    "tags": [
      "cat-accessory",
      "cat",
      "litter-and-waste-disposal",
      "litter",
      "dr.-elsey's"
    ]
  },
  {
    "sku": "petsmart-5333483",
    "tags": [
      "cat-accessory",
      "cat",
      "collars-harnesses-and-leashes",
      "collars",
      "made-by-cleo"
    ]
  },
  {
    "sku": "petsmart-5307818",
    "tags": [
      "cat-accessory",
      "cat",
      "bowls-and-feeders",
      "automatic-feeders",
      "catit-pixi-smart-cat-feeder-62724-html",
      "catit"
    ]
  },
  {
    "sku": "petsmart-5333564",
    "tags": [
      "cat-accessory",
      "cat",
      "collars-harnesses-and-leashes",
      "collars",
      "made-by-cleo"
    ]
  },
  {
    "sku": "petsmart-5138724",
    "tags": [
      "cat-accessory",
      "featured-shops",
      "adoption-kit-cat",
      "adult",
      "whisker-city-hooded-cat-bed-5538-html",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5206517",
    "tags": [
      "cat-accessory",
      "cat",
      "crates-gates-and-containment",
      "pens",
      "iris-3-tier-wire-cat-playpen-25962-html",
      "iris"
    ]
  },
  {
    "sku": "petsmart-5286668",
    "tags": [
      "cat-accessory",
      "cat",
      "litter-and-waste-disposal",
      "litter-boxes",
      "nature's-miracle"
    ]
  },
  {
    "sku": "petsmart-5311657",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "covered-beds",
      "armarkat"
    ]
  },
  {
    "sku": "petsmart-5297145",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "furniture-and-towers",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5326091",
    "tags": [
      "cat-accessory",
      "cat",
      "beds-and-furniture",
      "scratchers",
      "pets-first"
    ]
  },
  {
    "sku": "amazon-pet-B0B39B1FCR",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-scoops",
      "pet-believe",
      "asin-B0B39B1FCR"
    ]
  },
  {
    "sku": "amazon-pet-B082TPWZ4Y",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "harnesses",
      "azuza",
      "asin-B082TPWZ4Y"
    ]
  },
  {
    "sku": "amazon-pet-B0977KHTNR",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "optimuss",
      "asin-B0977KHTNR"
    ]
  },
  {
    "sku": "amazon-pet-B09SY7RMKM",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "haowecib",
      "asin-B09SY7RMKM"
    ]
  },
  {
    "sku": "amazon-pet-B07PK3QFT4",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "beds",
      "visit-the-sri-store",
      "asin-B07PK3QFT4"
    ]
  },
  {
    "sku": "amazon-pet-B0B4T828SG",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter",
      "worem",
      "asin-B0B4T828SG"
    ]
  },
  {
    "sku": "amazon-pet-B08F48TT7W",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "visit-the-pet-believe-store",
      "asin-B08F48TT7W"
    ]
  },
  {
    "sku": "amazon-pet-B0844NY3B5",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "harnesses",
      "best-pet-supplies",
      "asin-B0844NY3B5"
    ]
  },
  {
    "sku": "amazon-pet-B0B1J97MBX",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "generic",
      "asin-B0B1J97MBX"
    ]
  },
  {
    "sku": "amazon-pet-B086BMK3LW",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-boxes",
      "scenereal",
      "asin-B086BMK3LW"
    ]
  },
  {
    "sku": "amazon-pet-B09NXY4WV7",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "toys",
      "feather-toys",
      "generic",
      "asin-B09NXY4WV7"
    ]
  },
  {
    "sku": "amazon-pet-B09WRWH281",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "pups&pets",
      "asin-B09WRWH281"
    ]
  },
  {
    "sku": "amazon-pet-B09NWDK9GX",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "urchin",
      "asin-B09NWDK9GX"
    ]
  },
  {
    "sku": "amazon-pet-B09LYPZ133",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-posts",
      "ubersweet",
      "asin-B09LYPZ133"
    ]
  },
  {
    "sku": "amazon-pet-B09QSSVKWQ",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-boxes",
      "visit-the-pets-empire-store",
      "asin-B09QSSVKWQ"
    ]
  },
  {
    "sku": "amazon-pet-B0B58J6BGS",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-boxes",
      "generic",
      "asin-B0B58J6BGS"
    ]
  },
  {
    "sku": "amazon-pet-B09ZRW3N6J",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-boxes",
      "bizofft",
      "asin-B09ZRW3N6J"
    ]
  },
  {
    "sku": "amazon-pet-B01BG1UZG0",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter",
      "smiling-paws-pets",
      "asin-B01BG1UZG0"
    ]
  },
  {
    "sku": "amazon-pet-B0B1J9TJC6",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "generic",
      "asin-B0B1J9TJC6"
    ]
  },
  {
    "sku": "amazon-pet-B09815R5F3",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "harnesses",
      "dimu",
      "asin-B09815R5F3"
    ]
  },
  {
    "sku": "amazon-pet-B091Q5WKTR",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-scoops",
      "visit-the-emily-pets-store",
      "asin-B091Q5WKTR"
    ]
  },
  {
    "sku": "amazon-pet-B07PV32FSD",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "buckle-down",
      "asin-B07PV32FSD"
    ]
  },
  {
    "sku": "amazon-pet-B07FD8TWG5",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "beds",
      "kitty-city",
      "asin-B07FD8TWG5"
    ]
  },
  {
    "sku": "amazon-pet-B09L7CGJLG",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "fabater",
      "asin-B09L7CGJLG"
    ]
  },
  {
    "sku": "amazon-pet-B07F3DFPY3",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "trees",
      "vesper",
      "asin-B07F3DFPY3"
    ]
  },
  {
    "sku": "amazon-pet-B0B6VBN4C9",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "visit-the-emily-pets-store",
      "asin-B0B6VBN4C9"
    ]
  },
  {
    "sku": "amazon-pet-B097HDW7V4",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "hui",
      "asin-B097HDW7V4"
    ]
  },
  {
    "sku": "amazon-pet-B07F3MD7M7",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "trees",
      "vesper",
      "asin-B07F3MD7M7"
    ]
  },
  {
    "sku": "amazon-pet-B07NWRR2SP",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-posts",
      "scratchme",
      "asin-B07NWRR2SP"
    ]
  },
  {
    "sku": "amazon-pet-B08NF25PDJ",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter",
      "visit-the-pets-empire-store",
      "asin-B08NF25PDJ"
    ]
  },
  {
    "sku": "amazon-pet-B0B1ZML728",
    "tags": [
      "cat-accessory",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter",
      "curlin",
      "asin-B0B1ZML728"
    ]
  },
  {
    "sku": "aliexpress-pet-00000",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00010",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00018",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00034",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00035",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00042",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00050",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00060",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00106",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00107",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00108",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00118",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00119",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00125",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00138",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00175",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00198",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00245",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00264",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00282",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00322",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00345",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00346",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00351",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00365",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00386",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00425",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00467",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00475",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00482",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00486",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00493",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00557",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00563",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00578",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00595",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00604",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00606",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00624",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-00628",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00666",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00674",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00691",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00724",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00727",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00765",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00769",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00778",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00786",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00787",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00796",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00812",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00823",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00825",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00848",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00863",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00868",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00880",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00917",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00937",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00941",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00968",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00975",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00988",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00996",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01073",
    "tags": [
      "cat-accessory"
    ]
  },
  {
    "sku": "aliexpress-pet-01096",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01131",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01141",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01148",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01150",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01159",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01170",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01182",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01232",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01261",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01302",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01317",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01326",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01333",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01365",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01374",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01402",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01407",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01418",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01430",
    "tags": [
      "cat-accessory",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01476",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01509",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01524",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01526",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01551",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01556",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01589",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01617",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01635",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01673",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01721",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01781",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01790",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01798",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01814",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01821",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01885",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01906",
    "tags": [
      "cat-accessory",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01935",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01957",
    "tags": [
      "cat-accessory",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01959",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01964",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01968",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01979",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01991",
    "tags": [
      "cat-accessory",
      "popular",
      "best-seller"
    ]
  }
];

export default entries;