// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-treat  |  Products: 39

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-202168",
    "tags": [
      "cat-treat",
      "cat",
      "toys",
      "balls-chasers",
      "turbo"
    ]
  },
  {
    "sku": "petsmart-5298156",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "great-choice"
    ]
  },
  {
    "sku": "petsmart-5322882",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "delectables"
    ]
  },
  {
    "sku": "petsmart-5321199",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "viva-la-kitty"
    ]
  },
  {
    "sku": "petsmart-5222190",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "purebites"
    ]
  },
  {
    "sku": "amazon-pet-B07XCFWHBR",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "visit-the-petlicious-&-more-store",
      "asin-B07XCFWHBR"
    ]
  },
  {
    "sku": "amazon-pet-B0B6W5K1G9",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "generic",
      "asin-B0B6W5K1G9"
    ]
  },
  {
    "sku": "amazon-pet-B09BQY598C",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "mice-animal-toys",
      "visit-the-rvpaws-store",
      "asin-B09BQY598C"
    ]
  },
  {
    "sku": "amazon-pet-B001HWFIZM",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "ourpet'-s",
      "asin-B001HWFIZM"
    ]
  },
  {
    "sku": "amazon-pet-B09MZ4P67K",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "treats",
      "snacks",
      "visit-the-trixie-store",
      "asin-B09MZ4P67K"
    ]
  },
  {
    "sku": "aliexpress-pet-00021",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00077",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00136",
    "tags": [
      "cat-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00158",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00295",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00313",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00317",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00356",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00474",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00638",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00686",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00833",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00889",
    "tags": [
      "cat-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00932",
    "tags": [
      "cat-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00955",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01031",
    "tags": [
      "cat-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01166",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01171",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01221",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01283",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01332",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01337",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01341",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01356",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01372",
    "tags": [
      "cat-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01611",
    "tags": [
      "cat-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01801",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01854",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01867",
    "tags": [
      "cat-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  }
];

export default entries;