// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-health  |  Products with image: 10 (1 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-251342",
    "tags": [
      "cat-health",
      "cat",
      "vitamins-supplements",
      "immune-system-allergy",
      "soft-chews-wafers-chewable-tablets",
      "gnc-pets",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "petsmart-5317010",
    "tags": [
      "cat-health",
      "pharmacy",
      "cat",
      "anxiety-and-calming",
      "sandoz"
    ]
  },
  {
    "sku": "petsmart-5316871",
    "tags": [
      "cat-health",
      "pharmacy",
      "cat",
      "medical-supplies",
      "merck-animal-health"
    ]
  },
  {
    "sku": "petsmart-5072130",
    "tags": [
      "cat-health",
      "cat",
      "food-and-treats",
      "veterinary-diets",
      "hill's-prescription-diet"
    ]
  },
  {
    "sku": "petsmart-5317015",
    "tags": [
      "cat-health",
      "pharmacy",
      "cat",
      "arthritis-and-pain-relief",
      "transcend-6-ml-vial-66962-html",
      "hytryl"
    ]
  },
  {
    "sku": "petsmart-5320624",
    "tags": [
      "cat-health",
      "cat",
      "dental-care-and-wellness",
      "treatments",
      "vet-worthy"
    ]
  },
  {
    "sku": "petsmart-5072073",
    "tags": [
      "cat-health",
      "cat",
      "food-and-treats",
      "veterinary-diets",
      "hill's-prescription-diet"
    ]
  },
  {
    "sku": "petsmart-5317160",
    "tags": [
      "cat-health",
      "pharmacy",
      "cat",
      "antibiotics",
      "vetone"
    ]
  },
  {
    "sku": "petsmart-5317306",
    "tags": [
      "cat-health",
      "pharmacy",
      "cat",
      "dewormers-and-parasite-care",
      "droncit"
    ]
  },
  {
    "sku": "petsmart-5181810",
    "tags": [
      "cat-health",
      "cat",
      "dental-care-and-wellness",
      "treatments",
      "thundershirt"
    ]
  }
];

export default entries;