// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: cat-treat  |  Products with image: 10 (0 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-202168",
    "tags": [
      "cat-treat",
      "cat",
      "toys",
      "balls-chasers",
      "turbo"
    ]
  },
  {
    "sku": "petsmart-5298156",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "great-choice"
    ]
  },
  {
    "sku": "petsmart-5322882",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "delectables"
    ]
  },
  {
    "sku": "petsmart-5321199",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "viva-la-kitty"
    ]
  },
  {
    "sku": "petsmart-5222190",
    "tags": [
      "cat-treat",
      "cat",
      "food-and-treats",
      "treats",
      "purebites"
    ]
  },
  {
    "sku": "amazon-pet-B07XCFWHBR",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "visit-the-petlicious-&-more-store",
      "asin-B07XCFWHBR"
    ]
  },
  {
    "sku": "amazon-pet-B0B6W5K1G9",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "generic",
      "asin-B0B6W5K1G9"
    ]
  },
  {
    "sku": "amazon-pet-B09BQY598C",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "mice-animal-toys",
      "visit-the-rvpaws-store",
      "asin-B09BQY598C"
    ]
  },
  {
    "sku": "amazon-pet-B001HWFIZM",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "ourpet'-s",
      "asin-B001HWFIZM"
    ]
  },
  {
    "sku": "amazon-pet-B09MZ4P67K",
    "tags": [
      "cat-treat",
      "pet-supplies",
      "cats",
      "treats",
      "snacks",
      "visit-the-trixie-store",
      "asin-B09MZ4P67K"
    ]
  }
];

export default entries;