// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-health  |  Products with image: 32 (10 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-298272",
    "tags": [
      "dog-health",
      "dog",
      "vitamins-supplements",
      "hip-joint",
      "naturvet"
    ]
  },
  {
    "sku": "chewy-163975",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "natural-chews",
      "icelandic+",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-306771",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "dental-treats",
      "true-acre-foods",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-88080",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "bones",
      "nature's-logic",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-249406",
    "tags": [
      "dog-health",
      "dog",
      "vitamins-supplements",
      "hip-joint",
      "zesty-paws",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-314348",
    "tags": [
      "dog-health",
      "dog",
      "healthcare",
      "natura-petz-organics",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-180114",
    "tags": [
      "dog-health",
      "dog",
      "flea-tick",
      "home-yard-treatments",
      "yard-treatments",
      "liquid-fence",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-348205",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog-pharmacy",
      "respiratory-care-asthma",
      "azithromycin-compounded",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-111085",
    "tags": [
      "dog-health",
      "dog",
      "healthcare",
      "dental-care",
      "brushless-teeth-cleaning",
      "oravet"
    ]
  },
  {
    "sku": "petsmart-5316201",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "flea-and-tick",
      "credelio"
    ]
  },
  {
    "sku": "petsmart-5316842",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "arthritis-and-pain-relief",
      "quellin"
    ]
  },
  {
    "sku": "petsmart-5313161",
    "tags": [
      "dog-health",
      "dog",
      "dental-care-and-wellness",
      "dental-care",
      "oravet"
    ]
  },
  {
    "sku": "petsmart-5317382",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "digestive-tract-liver-and-pancreas",
      "baxter"
    ]
  },
  {
    "sku": "petsmart-5323400",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "dental-treats",
      "pedigree"
    ]
  },
  {
    "sku": "petsmart-5295986",
    "tags": [
      "dog-health",
      "dog",
      "dental-care-and-wellness",
      "treatments",
      "silver-honey"
    ]
  },
  {
    "sku": "petsmart-5296573",
    "tags": [
      "dog-health",
      "dog",
      "food",
      "veterinary-diets",
      "hill's-prescription-diet"
    ]
  },
  {
    "sku": "petsmart-5323401",
    "tags": [
      "dog-health",
      "featured-brands",
      "pedigree"
    ]
  },
  {
    "sku": "petsmart-5309817",
    "tags": [
      "dog-health",
      "dog",
      "dental-care-and-wellness",
      "treatments",
      "calm-paws"
    ]
  },
  {
    "sku": "petsmart-5271986",
    "tags": [
      "dog-health",
      "dog",
      "flea-and-tick",
      "spot-ons",
      "petarmor"
    ]
  },
  {
    "sku": "petsmart-5322604",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "dental-treats",
      "ark-naturals"
    ]
  },
  {
    "sku": "petsmart-5317145",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "immune-support",
      "piroxicam"
    ]
  },
  {
    "sku": "petsmart-5317302",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "skin-and-coat-care",
      "muricin"
    ]
  },
  {
    "sku": "petsmart-5288667",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "dental-treats",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5312934",
    "tags": [
      "dog-health",
      "dog",
      "dental-care-and-wellness",
      "vitamins-and-supplements",
      "vetiq"
    ]
  },
  {
    "sku": "petsmart-5315994",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "arthritis-and-pain-relief",
      "previcox"
    ]
  },
  {
    "sku": "petsmart-5323254",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "dental-treats",
      "ark-naturals"
    ]
  },
  {
    "sku": "petsmart-5319482",
    "tags": [
      "dog-health",
      "dog",
      "dental-care-and-wellness",
      "treatments",
      "dog-mx"
    ]
  },
  {
    "sku": "petsmart-5287577",
    "tags": [
      "dog-health",
      "dog",
      "treats",
      "dental-treats",
      "whimzees"
    ]
  },
  {
    "sku": "petsmart-5317291",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "ear-and-eye-care",
      "sandoz"
    ]
  },
  {
    "sku": "petsmart-5118450",
    "tags": [
      "dog-health",
      "dog",
      "food",
      "veterinary-diets",
      "hill's-prescription-diet"
    ]
  },
  {
    "sku": "petsmart-5295661",
    "tags": [
      "dog-health",
      "dog",
      "grooming-supplies",
      "brushes-combs-and-blowdryers",
      "top-paw-flea-pet-comb-57786-html",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5316137",
    "tags": [
      "dog-health",
      "pharmacy",
      "dog",
      "immune-support",
      "palladia"
    ]
  }
];

export default entries;