// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-treat  |  Products with image: 19 (5 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-212217",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "biscuits-cookies-crunchy-treats",
      "bark-bars",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-579502",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "hard-chews",
      "pet-'n-shape",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-141981",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "soft-chewy-treats",
      "top-rated",
      "bil-jac",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-320004",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "natural-chews",
      "k9warehouse",
      "has-ingredients"
    ]
  },
  {
    "sku": "petsmart-5291357",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "dentley's"
    ]
  },
  {
    "sku": "petsmart-5318646",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5266079",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "smartbones"
    ]
  },
  {
    "sku": "petsmart-5313055",
    "tags": [
      "dog-treat",
      "dog",
      "food",
      "frozen-food",
      "ben-&amp;-jerry's"
    ]
  },
  {
    "sku": "petsmart-5308328",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "petstages"
    ]
  },
  {
    "sku": "petsmart-5324360",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "playology"
    ]
  },
  {
    "sku": "petsmart-5304000",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5307981",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "roam"
    ]
  },
  {
    "sku": "petsmart-5307873",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "nylabone"
    ]
  },
  {
    "sku": "petsmart-5294973",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "roam"
    ]
  },
  {
    "sku": "petsmart-5133345",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "busy-bone"
    ]
  },
  {
    "sku": "petsmart-5303999",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5324611",
    "tags": [
      "dog-treat",
      "dog",
      "training-and-behavior",
      "training-and-behavior-accessories",
      "top-paw"
    ]
  },
  {
    "sku": "amazon-pet-B08GPRHBDH",
    "tags": [
      "dog-treat",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "hamiledyi",
      "asin-B08GPRHBDH"
    ]
  },
  {
    "sku": "amazon-pet-B0B5H6T4MJ",
    "tags": [
      "dog-treat",
      "pet-supplies",
      "cats",
      "food",
      "dry",
      "canine-india",
      "asin-B0B5H6T4MJ"
    ]
  }
];

export default entries;