// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-toy  |  Products with image: 28 (11 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-155129",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "unstuffed-toys",
      "mighty"
    ]
  },
  {
    "sku": "chewy-267852",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "rope-tug-toys",
      "marvel"
    ]
  },
  {
    "sku": "chewy-222514",
    "tags": [
      "dog-toy",
      "dog",
      "beds",
      "bolster-beds",
      "furhaven"
    ]
  },
  {
    "sku": "chewy-82848",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "balls",
      "hartz"
    ]
  },
  {
    "sku": "chewy-361434",
    "tags": [
      "dog-toy",
      "dog",
      "cleaning-potty",
      "poop-bags-scoopers",
      "poop-bags",
      "doggy-do-good"
    ]
  },
  {
    "sku": "petsmart-5308133",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5327517",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5300089",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5327453",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5305745",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5323969",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "joyhound"
    ]
  },
  {
    "sku": "petsmart-5243938",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5233933",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5310627",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "thrills-&amp;-chills"
    ]
  },
  {
    "sku": "petsmart-5327451",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5305766",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5325000",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "netflix"
    ]
  },
  {
    "sku": "petsmart-5308496",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "nerf-dog"
    ]
  },
  {
    "sku": "petsmart-5308281",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "kong"
    ]
  },
  {
    "sku": "petsmart-5147120",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "rope-and-tug-toys",
      "kong"
    ]
  },
  {
    "sku": "amazon-pet-B09TH4F4TV",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "ubersweet",
      "asin-B09TH4F4TV"
    ]
  },
  {
    "sku": "amazon-pet-B0993M5LLL",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "kapoor-pets",
      "asin-B0993M5LLL"
    ]
  },
  {
    "sku": "amazon-pet-B095N4JCG8",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-blankets",
      "visit-the-petslover-store",
      "asin-B095N4JCG8"
    ]
  },
  {
    "sku": "amazon-pet-B06XXZCZ5F",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "joyelf",
      "asin-B06XXZCZ5F"
    ]
  },
  {
    "sku": "amazon-pet-B09KRSM8DD",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "ubersweet",
      "asin-B09KRSM8DD"
    ]
  },
  {
    "sku": "amazon-pet-B09L77VYDS",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "fabater",
      "asin-B09L77VYDS"
    ]
  },
  {
    "sku": "amazon-pet-B07DQ5DZB9",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "beds",
      "bessie-and-barnie",
      "asin-B07DQ5DZB9"
    ]
  },
  {
    "sku": "amazon-pet-B09C5HLCQQ",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "dog-trust",
      "asin-B09C5HLCQQ"
    ]
  }
];

export default entries;