// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-wet-food  |  Products with image: 21 (141 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-356840",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "chewy-71333",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "health-extension",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-67635",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "purina-pro-plan",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-98911",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "merrick",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-639406",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "premium-food",
      "freeze-dried-food",
      "purebites",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-235070",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "livelong-healthy-&-strong",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "petsmart-5067364",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "purina-pro-plan"
    ]
  },
  {
    "sku": "petsmart-5158760",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "great-choice"
    ]
  },
  {
    "sku": "petsmart-5247762",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5246994",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5288828",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "canidae"
    ]
  },
  {
    "sku": "petsmart-5282601",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "nature's-recipe"
    ]
  },
  {
    "sku": "petsmart-5230981",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "nutro"
    ]
  },
  {
    "sku": "petsmart-5166487",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5083856",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "veterinary-diets",
      "royal-canin-veterinary-diet"
    ]
  },
  {
    "sku": "petsmart-5281218",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "solid-gold"
    ]
  },
  {
    "sku": "petsmart-5200131",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "amazon-pet-B0B42LQRYT",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "generic",
      "asin-B0B42LQRYT"
    ]
  },
  {
    "sku": "amazon-pet-B09QQD38ZY",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "birds",
      "food",
      "comtim",
      "asin-B09QQD38ZY"
    ]
  },
  {
    "sku": "amazon-pet-B0B42Q8PHN",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B42Q8PHN"
    ]
  },
  {
    "sku": "amazon-pet-B0B42NBR66",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B42NBR66"
    ]
  }
];

export default entries;