// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-treat  |  Products: 235

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-676822",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "natural-chews",
      "pet-factory",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-212217",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "biscuits-cookies-crunchy-treats",
      "bark-bars",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "chewy-82721",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "fetch-toys",
      "balls",
      "hartz"
    ]
  },
  {
    "sku": "chewy-579502",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "hard-chews",
      "pet-'n-shape",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-141981",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "soft-chewy-treats",
      "top-rated",
      "bil-jac",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-320004",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "natural-chews",
      "k9warehouse",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-73683",
    "tags": [
      "dog-treat",
      "cat",
      "food",
      "raw-food",
      "wysong",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "petsmart-5291357",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "dentley's"
    ]
  },
  {
    "sku": "petsmart-5318646",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5277811",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "dentley's"
    ]
  },
  {
    "sku": "petsmart-5266079",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "smartbones"
    ]
  },
  {
    "sku": "petsmart-5313055",
    "tags": [
      "dog-treat",
      "dog",
      "food",
      "frozen-food",
      "ben-&amp;-jerry's"
    ]
  },
  {
    "sku": "petsmart-5308328",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "petstages"
    ]
  },
  {
    "sku": "petsmart-5324360",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "playology"
    ]
  },
  {
    "sku": "petsmart-5304000",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5307981",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "roam"
    ]
  },
  {
    "sku": "petsmart-5307873",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "nylabone"
    ]
  },
  {
    "sku": "petsmart-5294973",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "roam"
    ]
  },
  {
    "sku": "petsmart-5133345",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "bones-and-rawhide",
      "busy-bone"
    ]
  },
  {
    "sku": "petsmart-5303999",
    "tags": [
      "dog-treat",
      "dog",
      "toys",
      "chew-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5307335",
    "tags": [
      "dog-treat",
      "dog",
      "treats",
      "jerky",
      "great-choice"
    ]
  },
  {
    "sku": "petsmart-5324611",
    "tags": [
      "dog-treat",
      "dog",
      "training-and-behavior",
      "training-and-behavior-accessories",
      "top-paw"
    ]
  },
  {
    "sku": "amazon-pet-B08GPRHBDH",
    "tags": [
      "dog-treat",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "hamiledyi",
      "asin-B08GPRHBDH"
    ]
  },
  {
    "sku": "amazon-pet-B0B5H6T4MJ",
    "tags": [
      "dog-treat",
      "pet-supplies",
      "cats",
      "food",
      "dry",
      "canine-india",
      "asin-B0B5H6T4MJ"
    ]
  },
  {
    "sku": "aliexpress-pet-00007",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00025",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00036",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00037",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00063",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00068",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00073",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00076",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00087",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00096",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00110",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00149",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00161",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00162",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00172",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00181",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00184",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00185",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00190",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00196",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00197",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00201",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00203",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00212",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00215",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00231",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00240",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00241",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00249",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00257",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00270",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00272",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00281",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00284",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00285",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00288",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00306",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00321",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00324",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00329",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00332",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00338",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00352",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00353",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00354",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00360",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00361",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00368",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00387",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00389",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00440",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00443",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00450",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00459",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00500",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00504",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00507",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00510",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00517",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00532",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00567",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00581",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00598",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00602",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00607",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00609",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00621",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00622",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00644",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00651",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00677",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00679",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00694",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00698",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00705",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00721",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00723",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00725",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00728",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00731",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00732",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00734",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00737",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00739",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00758",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00815",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00834",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00842",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00843",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00856",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00891",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00920",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00928",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00943",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00946",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00962",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00964",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00970",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00978",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00989",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-00990",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01019",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01028",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01030",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01038",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01055",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01057",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01063",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01067",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01076",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01083",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01086",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01087",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01110",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01111",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01117",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01127",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01128",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01130",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01137",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01140",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01154",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01162",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01175",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01176",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01178",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01180",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01185",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01195",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01213",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01217",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01220",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01225",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01227",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01229",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01235",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01256",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01259",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01260",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01277",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01298",
    "tags": [
      "dog-treat",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01305",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01307",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01327",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01335",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01336",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01339",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01344",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01347",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01350",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01353",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01360",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01370",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01376",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01381",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01384",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01385",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01386",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01404",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01410",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01411",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01422",
    "tags": [
      "dog-treat"
    ]
  },
  {
    "sku": "aliexpress-pet-01425",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01427",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01466",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01483",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01490",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01492",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01496",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01515",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01520",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01572",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01579",
    "tags": [
      "dog-treat",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01581",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01582",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01596",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01601",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01606",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01612",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01627",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01633",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01634",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01649",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01657",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01660",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01676",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01678",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01679",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01682",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01705",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01715",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01723",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01728",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01745",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01751",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01774",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01804",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01808",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01830",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01839",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01849",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01851",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01857",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01866",
    "tags": [
      "dog-treat",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01878",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01880",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01891",
    "tags": [
      "dog-treat",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01894",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01904",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01971",
    "tags": [
      "dog-treat",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01977",
    "tags": [
      "dog-treat",
      "popular"
    ]
  }
];

export default entries;