// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-dry-food  |  Products: 404

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-132261",
    "tags": [
      "dog-dry-food",
      "dog",
      "clothing-accessories",
      "accessories",
      "backpacks",
      "onetigris"
    ]
  },
  {
    "sku": "chewy-52719",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "hill's-science-diet",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-76718",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "eagle-pack",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-215356",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "hill's-science-diet",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-733462",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "high-protein",
      "blue-buffalo",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-46926",
    "tags": [
      "dog-dry-food",
      "dog",
      "treats",
      "biscuits-cookies-crunchy-treats",
      "blue-buffalo",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-90977",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "premium-food",
      "petkind",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-715630",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "premium-food",
      "dehydrated-food",
      "the-honest-kitchen"
    ]
  },
  {
    "sku": "chewy-213621",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "high-protein",
      "american-journey",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-93046",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "victor",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-295188",
    "tags": [
      "dog-dry-food",
      "dog",
      "carriers-travel",
      "travel-bowls-bags",
      "mobile-dog-gear"
    ]
  },
  {
    "sku": "chewy-292712",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "chewy-267891",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "premium-food",
      "acana",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-318128",
    "tags": [
      "dog-dry-food",
      "dog",
      "toys",
      "interactive-toys",
      "treat-toys-dispensers",
      "hanamya"
    ]
  },
  {
    "sku": "chewy-it’s an easy way to pack your pooch’s diet with nutrients",
    "tags": [
      "dog-dry-food",
      "'https://image.chewy.com/is/image/catalog/567726_pt1._ac_ss500_v1657659988_.jpg'"
    ]
  },
  {
    "sku": "petsmart-5329365",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "chicken-soup-for-the-soul"
    ]
  },
  {
    "sku": "petsmart-5266326",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "food-toppers",
      "wellness"
    ]
  },
  {
    "sku": "petsmart-5209448",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5301414",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "only-natural-pet"
    ]
  },
  {
    "sku": "petsmart-5314875",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "veterinary-diets",
      "blue-buffalo-natural-veterinary-diet"
    ]
  },
  {
    "sku": "petsmart-5180506",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "purina-one"
    ]
  },
  {
    "sku": "petsmart-5299403",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5248205",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "instinct"
    ]
  },
  {
    "sku": "petsmart-5177228",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "nature's-recipe"
    ]
  },
  {
    "sku": "petsmart-5278690",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "authority"
    ]
  },
  {
    "sku": "petsmart-5286363",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "eukanuba"
    ]
  },
  {
    "sku": "petsmart-5171472",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "wellness"
    ]
  },
  {
    "sku": "petsmart-5128755",
    "tags": [
      "dog-dry-food",
      "dog",
      "bowls-and-feeders",
      "food-and-water-bowls",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5306544",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5162673",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5313092",
    "tags": [
      "dog-dry-food",
      "dog",
      "bowls-and-feeders",
      "food-and-water-bowls",
      "mobile-dog-gear"
    ]
  },
  {
    "sku": "petsmart-5182763",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5258015",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "veterinary-diets",
      "purina-pro-plan-veterinary-diets"
    ]
  },
  {
    "sku": "petsmart-5329695",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "nutro-max"
    ]
  },
  {
    "sku": "petsmart-5306037",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "instinct"
    ]
  },
  {
    "sku": "petsmart-5301407",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "only-natural-pet"
    ]
  },
  {
    "sku": "petsmart-5299392",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5299381",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "amazon-pet-B08T7H2JPY",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B08T7H2JPY"
    ]
  },
  {
    "sku": "amazon-pet-B09FZ7MMTW",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "woofy",
      "asin-B09FZ7MMTW"
    ]
  },
  {
    "sku": "amazon-pet-B0B42MDFF5",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "cats",
      "food",
      "dry",
      "generic",
      "asin-B0B42MDFF5"
    ]
  },
  {
    "sku": "amazon-pet-B08T74ZSLC",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B08T74ZSLC"
    ]
  },
  {
    "sku": "aliexpress-pet-00011",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00023",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00033",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00053",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00086",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00143",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00156",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00173",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00194",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-00200",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00214",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00234",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00255",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00256",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00271",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00293",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00310",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00318",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00326",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00333",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00341",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00391",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-00396",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-00398",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00401",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00404",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00410",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00422",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00427",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00449",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00463",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00466",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00478",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00506",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00509",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00535",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00547",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00548",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00560",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00580",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00593",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00597",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00601",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00610",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00642",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00667",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-00688",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00695",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00713",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00745",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00809",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00821",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00836",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00846",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00850",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00854",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00865",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00866",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00867",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-00885",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00906",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00916",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00952",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00953",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00974",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00987",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01001",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01008",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-01036",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01056",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01065",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01105",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01119",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01124",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01125",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01138",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01152",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01158",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01163",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01187",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01194",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01207",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01209",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01243",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01248",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01267",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01268",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01306",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01316",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01321",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01340",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01369",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01377",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01387",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01401",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01409",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01414",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01441",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01443",
    "tags": [
      "dog-dry-food"
    ]
  },
  {
    "sku": "aliexpress-pet-01445",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01453",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01500",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01511",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01536",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01555",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01609",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01614",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01618",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01629",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01666",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01668",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01672",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01684",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01695",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01701",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01706",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01713",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01716",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01729",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01740",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01746",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01757",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01775",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01792",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01794",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01805",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01807",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01826",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01833",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01838",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01844",
    "tags": [
      "dog-dry-food",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01847",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01860",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01868",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01886",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01896",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01898",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01905",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01921",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01922",
    "tags": [
      "dog-dry-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01937",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01955",
    "tags": [
      "dog-dry-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01962",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01975",
    "tags": [
      "dog-dry-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-advanced-fitness-large-breed-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.3pct",
      "adult",
      "large-breed",
      "with-lamb-rice",
      "musculoskeletal-and-joint-care",
      "skin-health",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-mature-adult-7-plus-active-longevity-medium-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.1pct",
      "senior",
      "medium-breed",
      "with-chicken",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-td-mini-dry",
    "tags": [
      "dog-dry-food",
      "protein-16.1pct",
      "-",
      "small-breed",
      "with-chicken",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-puppy-healthy-development-medium-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.3pct",
      "puppy",
      "medium-breed",
      "with-chicken",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-dd-duck-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-15.1pct",
      "-",
      "with-duck-rice",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-advanced-fitness-large-breed-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-20.9pct",
      "adult",
      "large-breed",
      "with-chicken",
      "musculoskeletal-and-joint-care",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-mature-adult-7-plus-active-longevity-medium-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.2pct",
      "senior",
      "medium-breed",
      "with-lamb-rice",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-bd-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.3pct",
      "-",
      "with-chicken",
      "nervous-system-care-and-stress",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-ud-dry",
    "tags": [
      "dog-dry-food",
      "protein-10.2pct",
      "-",
      "original",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-td-dry",
    "tags": [
      "dog-dry-food",
      "protein-16.2pct",
      "-",
      "with-chicken",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-oral-care-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.7pct",
      "adult",
      "with-chicken",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-ld-dry",
    "tags": [
      "dog-dry-food",
      "protein-16.7pct",
      "-",
      "original",
      "liver-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-kd-dry",
    "tags": [
      "dog-dry-food",
      "protein-13.9pct",
      "-",
      "original",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-light-large-breed-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.3pct",
      "adult",
      "large-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-puppy-healthy-development-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.5pct",
      "puppy",
      "medium-breed",
      "lamb-and-rice",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-advanced-fitness-medium-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.4pct",
      "adult",
      "medium-breed",
      "with-lamb-rice",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-puppy-healthy-development-large-breed-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.8pct",
      "puppy",
      "large-breed",
      "with-chicken",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-cd-multicare-dry",
    "tags": [
      "dog-dry-food",
      "protein-20.0pct",
      "-",
      "with-chicken",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-id-stress-mini-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.9pct",
      "-",
      "small-breed",
      "with-chicken",
      "digestive-care",
      "nervous-system-care-and-stress",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-senior-mature-adult-small-mini-dog-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.2pct",
      "senior",
      "small-breed",
      "with-chicken",
      "aging-care",
      "nervous-system-care-and-stress",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-puppy-small-and-miniature-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.4pct",
      "puppy",
      "small-breed",
      "with-chicken",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-gastrointestinal-biome-canine-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.3pct",
      "-",
      "small-breed",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-senior-vitality-adult-7-plus-small-mini-chicken-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.8pct",
      "senior",
      "small-breed",
      "with-chicken-rice",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-perfect-digestion-large-breed-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.9pct",
      "puppy",
      "large-breed",
      "with-chicken-brown-rice",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-perfect-digestion-small-mini-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.6pct",
      "puppy",
      "small-breed",
      "with-chicken-brown-rice",
      "digestive-care",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-hypoallergenic-large-breed-adult-salmon-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.9pct",
      "adult",
      "large-breed",
      "with-salmon",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-perfect-digestion-medium-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.6pct",
      "puppy",
      "medium-breed",
      "with-chicken-brown-rice",
      "digestive-care",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-hypoallergenic-medium-adult-salmon-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.9pct",
      "adult",
      "medium-breed",
      "with-salmon",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-hypoallergenic-small-mini-adult-salmon-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.9pct",
      "-",
      "small-breed",
      "with-salmon",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-on-care-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-29.5pct",
      "-",
      "with-chicken",
      "cancer-patient-support",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-derm-complete-dry",
    "tags": [
      "dog-dry-food",
      "protein-16.9pct",
      "-",
      "original",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-metabolic-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.4pct",
      "-",
      "with-lamb-rice",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-mature-adult-6-plus-active-longevity-large-breed-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.8pct",
      "senior",
      "large-breed",
      "with-chicken",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-metabolic-plus-mobility-mini-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.7pct",
      "-",
      "small-breed",
      "with-chicken",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-weight-and-active-mobility-large-breed-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.5pct",
      "adult",
      "large-breed",
      "with-chicken",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-weight-and-active-mobility-small-mini-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.5pct",
      "adult",
      "small-breed",
      "with-chicken",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-digestion-small-mini-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.4pct",
      "adult",
      "small-breed",
      "with-chicken-and-brown-rice",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-adult-small-breed-with-lamb-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.5pct",
      "adult",
      "small-breed",
      "with-lamb-rice",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-neutereddog-adult-large-breed-dog-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.3pct",
      "adult",
      "large-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-healthy-digestive-biome-adult-large-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.1pct",
      "adult",
      "large-breed",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-healthy-digestive-biome-adult-small-mini-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.1pct",
      "adult",
      "small-breed",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-digestion-medium-breed-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.4pct",
      "adult",
      "medium-breed",
      "with-chicken-and-brown-rice",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-neutereddog-adult-small-breed-mini-dog-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.3pct",
      "adult",
      "small-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-derm-complete-mini-dry",
    "tags": [
      "dog-dry-food",
      "protein-16.9pct",
      "-",
      "small-breed",
      "original",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-adult-medium-with-lamb-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.5pct",
      "adult",
      "medium-breed",
      "with-lamb-rice",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-neutereddog-adult-medium-dog-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.3pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-small-breed-mini-puppy-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.0pct",
      "puppy",
      "small-breed",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-healthy-digestive-biome-adult-medium-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.1pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-weight-and-active-mobility-medium-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.9pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-kd-early-stage-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.4pct",
      "-",
      "original",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-gastrointestinal-biome-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.3pct",
      "adult",
      "with-chicken",
      "digestive-care",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-7-plus-light-medium-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.4pct",
      "senior",
      "medium-breed",
      "with-chicken",
      "weight-management",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-sensitive-stomach-and-skin-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.5pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-puppy-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.0pct",
      "puppy",
      "large-breed",
      "with-chicken",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-metabolic-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.3pct",
      "-",
      "small-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-small-and-miniature-lamb-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.4pct",
      "adult",
      "small-breed",
      "with-lamb-rice",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-healthy-mobility-large-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.6pct",
      "adult",
      "large-breed",
      "with-chicken",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-metabolic-original-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.3pct",
      "-",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-metabolic-plus-mobility-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.7pct",
      "-",
      "with-chicken",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-adult-mini-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.3pct",
      "adult",
      "small-breed",
      "with-chicken",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-canine-adult-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.3pct",
      "adult",
      "large-breed",
      "with-chicken",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-rd-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-31.1pct",
      "-",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-metabolic-plus-urinary-original-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.6pct",
      "-",
      "original",
      "urinary-care",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-perfect-weight-large-breed-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.4pct",
      "adult",
      "large-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-small-and-miniature-sensitive-stomach-skin-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.4pct",
      "adult",
      "small-breed",
      "with-chicken",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-jd-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.6pct",
      "-",
      "original",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-id-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.3pct",
      "-",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-light-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.6pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-healthy-mobility-mini-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.9pct",
      "adult",
      "small-breed",
      "with-chicken",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-senior-11-plus-small-and-miniature-original-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.7pct",
      "senior",
      "small-breed",
      "with-chicken",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-small-and-miniature-light-original-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.6pct",
      "adult",
      "small-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-advanced-fitness-med-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.1pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-perfect-weight-mini-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.5pct",
      "adult",
      "small-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-id-low-fat-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.8pct",
      "-",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-mature-adult-7-plus-small-and-miniature-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.9pct",
      "senior",
      "small-breed",
      "with-chicken",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-puppy-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.0pct",
      "puppy",
      "medium-breed",
      "with-chicken",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-small-and-miniature-chicken-turkey-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.7pct",
      "adult",
      "small-breed",
      "with-chicken",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-zd-mini-original-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.6pct",
      "-",
      "small-breed",
      "original",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-id-sensitive-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.9pct",
      "-",
      "with-egg-rice",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-mature-adult-7-plus-mini-light-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.4pct",
      "senior",
      "small-breed",
      "with-chicken",
      "weight-management",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-kd-plus-mobility-original-dry",
    "tags": [
      "dog-dry-food",
      "protein-14.0pct",
      "-",
      "original",
      "kidney-care",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-perfect-weight-medium-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.4pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-healthy-mobility-medium-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.6pct",
      "adult",
      "medium-breed",
      "with-chicken",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-senior-mature-adult-medium-large-dog-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.2pct",
      "senior",
      "large-breed",
      "with-chicken",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-wd-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-20.8pct",
      "-",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-jd-canine-reduced-calorie-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.5pct",
      "-",
      "with-chicken",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-digestion-large-breed-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.4pct",
      "adult",
      "large-breed",
      "with-chicken-and-brown-rice",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-puppy-derm-complete-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.4pct",
      "puppy",
      "original",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-zd-ultra-allergen-free-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.6pct",
      "-",
      "original",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-small-bites-chicken-brown-rice-oats-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "chicken-brown-rice-whole-oats-recipe",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-bites-no-corn-wheat-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.6pct",
      "adult",
      "chicken-brown-rice-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-senior-vitality-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.4pct",
      "senior",
      "small-breed",
      "chicken-meal-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-dd-canine-potato-and-venison-formula-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.5pct",
      "-",
      "potato-venison-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-dd-canine-potato-and-duck-formula-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.5pct",
      "-",
      "potato-duck-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-cd-multicare-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.3pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-zd-low-fat-hydrolyzed-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.0pct",
      "-",
      "hydrolyzed-soy-recipe",
      "food-sensitivity",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-lamb-meal-brown-rice-recipe-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.3pct",
      "puppy",
      "lamb-meal-brown-rice-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.3pct",
      "puppy",
      "large-breed",
      "chicken-brown-rice-recipe",
      "puppy-care",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.8pct",
      "puppy",
      "chicken-brown-rice-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.6pct",
      "-",
      "small-breed",
      "chicken-recipe",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.7pct",
      "-",
      "chicken-recipe",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.6pct",
      "-",
      "large-breed",
      "chicken-recipe",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-salmon-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "salmon-brown-rice-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-healthy-mobility-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.4pct",
      "-",
      "chicken-meal-brown-rice-barley",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.9pct",
      "adult",
      "large-breed",
      "chicken-barley-recipe",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-large-breed-no-corn-wheat-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.6pct",
      "adult",
      "large-breed",
      "chicken-brown-rice-recipe",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-light-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.3pct",
      "adult",
      "with-chicken-meal-barley",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-11-plus-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.5pct",
      "senior",
      "small-breed",
      "chicken-brown-rice-barley-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-6-plus-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.7pct",
      "senior",
      "large-breed",
      "chicken-meal-barley-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.7pct",
      "senior",
      "chicken-meal-barley-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-lamb-meal-brown-rice-recipe-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.4pct",
      "adult",
      "lamb-meal-brown-rice-recipe",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-rd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-33.9pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-td-canine-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.3pct",
      "-",
      "chicken-flavor",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-ud-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-13.8pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-td-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.3pct",
      "-",
      "chicken-flavor",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-plus-mobility-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.5pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-jd-small-bites-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-20.0pct",
      "-",
      "chicken-flavor",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-with-lamb-dry",
    "tags": [
      "dog-dry-food",
      "protein-15.8pct",
      "-",
      "with-lamb",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-jd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-20.0pct",
      "-",
      "chicken-flavor",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-15.6pct",
      "-",
      "with-chicken",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-dd-canine-skin-support-potato-and-salmon-formula-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.5pct",
      "-",
      "potato-salmon-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-gastrointestinal-biome-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.0pct",
      "-",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-gd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.5pct",
      "-",
      "chicken-flavor",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-hd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.8pct",
      "-",
      "chicken-flavor",
      "heart-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-cd-multicare-low-fat-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.0pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-bd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.1pct",
      "-",
      "chicken-flavor",
      "nervous-system-care-and-stress",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-no-corn-wheat-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-29.0pct",
      "puppy",
      "chicken-brown-rice-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-sensitive-stomach-and-skin-salmon-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-30.7pct",
      "puppy",
      "salmon-brown-rice-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-large-breed-lamb-meal-brown-rice-recipe-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.9pct",
      "puppy",
      "large-breed",
      "lamb-meal-brown-rice-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.8pct",
      "puppy",
      "chicken-brown-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.9pct",
      "puppy",
      "small-breed",
      "chicken-brown-rice-recipe",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-grain-free-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.9pct",
      "-",
      "chicken-potato-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-pollock-meal-insect-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.9pct",
      "-",
      "pollock-meal-insect-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "-",
      "large-breed",
      "chicken-barley-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-oral-care-small-mini-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.8pct",
      "-",
      "small-breed",
      "chicken-recipe",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-light-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.3pct",
      "adult",
      "with-chicken-meal-barley",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-light-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "small-breed",
      "chicken-meal-barley-brown-rice-recipe",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-no-corn-wheat-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.6pct",
      "adult",
      "chicken-brown-rice-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-perfect-digestion-small-bites-chicken-brown-rice-oats-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.0pct",
      "senior",
      "small-breed",
      "chicken-whole-oats-brown-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-perfect-digestion-chicken-brown-rice-oats-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.0pct",
      "senior",
      "chicken-whole-oats-brown-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-senior-vitality-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.6pct",
      "senior",
      "chicken-rice-recipe",
      "aging-care",
      "nervous-system-care-and-stress",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-no-corn-wheat-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.0pct",
      "senior",
      "chicken-brown-rice",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-zd-canine-small-bites-dog-food-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.8pct",
      "-",
      "original-flavor",
      "digestive-care",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-wd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-20.7pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-zd-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.8pct",
      "-",
      "original-flavor",
      "digestive-care",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-canine-lamb-meal-and-rice-formula-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.2pct",
      "-",
      "lamb-meal-rice-formula",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-plus-mobility-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-15.9pct",
      "-",
      "chicken-flavor",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-ld-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-18.1pct",
      "-",
      "chicken-flavor",
      "liver-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.0pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.7pct",
      "-",
      "chicken-flavor",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-small-bites-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.7pct",
      "-",
      "chicken-flavor",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-low-fat-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.1pct",
      "-",
      "chicken-flavor",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-stress-canine-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.1pct",
      "-",
      "small-breed",
      "chicken-flavor",
      "nervous-system-care-and-stress",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-cd-multicare-plus-metabolic-dry",
    "tags": [
      "dog-dry-food",
      "protein-27.5pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-puppy-derm-complete-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.5pct",
      "-",
      "rice-egg-recipe",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-onc-on-care-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-30.8pct",
      "-",
      "with-chicken",
      "cancer-patient-support",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-derm-complete-dry",
    "tags": [
      "dog-dry-food",
      "protein-17.3pct",
      "-",
      "rice-egg-recipe",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-bites-lamb-meal-brown-rice-recipe-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.4pct",
      "adult",
      "lamb-meal-brown-rice-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "-",
      "chicken-barley-recipe",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-26.0pct",
      "-",
      "small-breed",
      "chicken-recipe",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "small-breed",
      "chicken-meal-rice-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-large-breed-chicken-brown-rice-oats-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "large-breed",
      "chicken-brown-rice-whole-oats-recipe",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-joint-support-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.5pct",
      "-",
      "chicken-recipe",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-joint-support-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.5pct",
      "-",
      "large-breed",
      "chicken-recipe",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-small-mini-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.0pct",
      "adult",
      "small-breed",
      "chicken-brown-rice-recipe",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-salmon-oats-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "salmon-whole-oats-and-brown-rice-recipe",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-dry",
    "tags": [
      "dog-dry-food",
      "protein-28.6pct",
      "-",
      "chicken-recipe",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.0pct",
      "senior",
      "chicken-meal-barley-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-chicken-barley-entree-canned",
    "tags": [
      "dog-dry-food",
      "protein-26.5pct",
      "adult",
      "chicken-barley-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-chicken-beef-entree-canned",
    "tags": [
      "dog-dry-food",
      "protein-23.1pct",
      "adult",
      "chicken-beef-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-beef-barley-entree-canned",
    "tags": [
      "dog-dry-food",
      "protein-23.7pct",
      "adult",
      "beef-barley-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-small-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.5pct",
      "senior",
      "small-breed",
      "chicken-brown-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.8pct",
      "-",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "protein-24.0pct",
      "adult",
      "chicken-barley-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-large-breed-lamb-meal-brown-rice-recipe-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.4pct",
      "adult",
      "large-breed",
      "lamb-meal-brown-rice-recipe",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-light-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.3pct",
      "adult",
      "large-breed",
      "chicken-meal-barley-recipe",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-dry",
    "tags": [
      "dog-dry-food",
      "protein-23.8pct",
      "adult",
      "chicken-barley-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-breed-lamb-meal-brown-rice-recipe-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "adult",
      "small-breed",
      "lamb-meal-brown-rice-recipe",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-brain-care-plus-jd-chicken-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.2pct",
      "-",
      "with-chicken",
      "nervous-system-care-and-stress",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-multi-organ-dry",
    "tags": [
      "dog-dry-food",
      "protein-19.2pct",
      "-",
      "with-chicken",
      "urgent-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-oral-care-dry",
    "tags": [
      "dog-dry-food",
      "protein-25.0pct",
      "-",
      "chicken-rice-barley-recipe",
      "dental-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-healthy-mobility-large-breed-dry",
    "tags": [
      "dog-dry-food",
      "protein-22.4pct",
      "-",
      "large-breed",
      "chicken-meal-brown-rice-barley-recipe",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-turkey-barley-canned",
    "tags": [
      "dog-dry-food",
      "protein-22.6pct",
      "adult",
      "turkey-barley",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-6-plus-large-breed-no-corn-wheat-soy-dry",
    "tags": [
      "dog-dry-food",
      "protein-21.0pct",
      "senior",
      "large-breed",
      "chicken-brown-rice-recipe",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-kd-kidney-care-starter-kit-variety-pack",
    "tags": [
      "dog-dry-food",
      "protein-15.2pct",
      "-",
      "with-chicken",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-kd-with-chicken-canned",
    "tags": [
      "dog-dry-food",
      "kidney-care",
      "original",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-advanced-fitness-large-breed-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "adult",
      "large-breed-breed",
      "with-lamb-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-mature-adult-7-plus-active-longevity-medium-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "senior",
      "medium-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-td-mini-dry",
    "tags": [
      "dog-dry-food",
      "dental-care",
      "adult--senior",
      "small-breed--medium-breed--large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-puppy-healthy-development-medium-chicken-dry",
    "tags": [
      "dog-dry-food",
      "puppy-pregnant-nursing",
      "medium-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-dd-duck-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "skin-care",
      "adult--senior",
      "small-breed--medium-breed--large-breed-breed",
      "with-duck-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-advanced-fitness-large-breed-with-chicken-dry",
    "tags": [
      "dog-dry-food",
      "adult",
      "large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-mature-adult-7-plus-active-longevity-medium-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "senior",
      "medium-breed-breed",
      "with-lamb-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-bd-dry",
    "tags": [
      "dog-dry-food",
      "ageing-care",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-ud-dry",
    "tags": [
      "dog-dry-food",
      "urinary-care",
      "adult",
      "original",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-td-dry",
    "tags": [
      "dog-dry-food",
      "dental-care",
      "adult--senior",
      "small-breed--medium-breed--large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-oral-care-chicken-dry",
    "tags": [
      "dog-dry-food",
      "adult",
      "medium-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-ld-dry",
    "tags": [
      "dog-dry-food",
      "liver-care",
      "adult",
      "small-breed--medium-breed--large-breed-breed",
      "original",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-kd-dry",
    "tags": [
      "dog-dry-food",
      "kidney-care",
      "adult--senior",
      "large-breed--medium-breed--small-breed-breed",
      "original",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-light-large-breed-chicken-dry",
    "tags": [
      "dog-dry-food",
      "adult",
      "large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-puppy-healthy-development-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "puppy-pregnant-nursing",
      "medium-breed-breed",
      "lamb-and-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-advanced-fitness-medium-lamb-and-rice-dry",
    "tags": [
      "dog-dry-food",
      "adult",
      "medium-breed-breed",
      "with-lamb-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-puppy-healthy-development-large-breed-chicken-dry",
    "tags": [
      "dog-dry-food",
      "puppy-pregnant-nursing",
      "large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-hills-canine-healthy-weight-dog-treats",
    "tags": [
      "dog-dry-food",
      "adult-1-",
      "hills"
    ]
  },
  {
    "sku": "hills-hills-canine-hypoallergenic-dog-treats",
    "tags": [
      "dog-dry-food",
      "adult-1-",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-cd-multicare-dry",
    "tags": [
      "dog-dry-food",
      "urinary-care",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-id-stress-mini-chicken-dry",
    "tags": [
      "dog-dry-food",
      "digestive-care",
      "adult--senior",
      "small-breed--medium-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-ve-canine-vetessentials-senior-mature-adult-small-mini-dog-food-chicken-dry",
    "tags": [
      "dog-dry-food",
      "ageing-care",
      "senior",
      "small-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-puppy-small-and-miniature-chicken-dry",
    "tags": [
      "dog-dry-food",
      "puppy-pregnant-nursing",
      "small-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-gastrointestinal-biome-canine-small-bites-dry",
    "tags": [
      "dog-dry-food",
      "digestive-care",
      "adult--senior",
      "small-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-senior-vitality-adult-7-plus-small-mini-chicken-rice-dry",
    "tags": [
      "dog-dry-food",
      "senior",
      "small-breed-breed",
      "with-chicken-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sd-canine-puppy-perfect-digestion-large-breed-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "digestive-care",
      "puppy-pregnant-nursing",
      "large-breed-breed",
      "with-chicken-brown-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sd-canine-puppy-perfect-digestion-small-mini-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "digestive-care",
      "puppy-pregnant-nursing",
      "small-breed-breed",
      "with-chicken-brown-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-hypoallergenic-large-breed-adult-salmon-dry",
    "tags": [
      "dog-dry-food",
      "adult-1-5",
      "adult",
      "large-breed-breed",
      "with-salmon",
      "hills"
    ]
  },
  {
    "sku": "hills-sd-canine-puppy-perfect-digestion-medium-chicken-brown-rice-dry",
    "tags": [
      "dog-dry-food",
      "digestive-care",
      "puppy-pregnant-nursing",
      "medium-breed-breed",
      "with-chicken-brown-rice",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-hypoallergenic-medium-adult-salmon-dry",
    "tags": [
      "dog-dry-food",
      "adult-1-6",
      "adult",
      "medium-breed-breed",
      "with-salmon",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-hypoallergenic-small-mini-adult-salmon-dry",
    "tags": [
      "dog-dry-food",
      "food-sensitivities",
      "adult",
      "small-breed-breed",
      "with-salmon",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-gastrointestinal-biome-with-chicken-canned",
    "tags": [
      "dog-dry-food",
      "digestive-care",
      "with-chicken",
      "hills"
    ]
  }
];

export default entries;