// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-wet-food  |  Products: 168

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-100126",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "purina-beneful",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-263290",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "premium-food",
      "freeze-dried-food",
      "ketogenic-pet-food",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-356840",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "chewy-131107",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "lotus",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-71333",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "health-extension",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-67635",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "purina-pro-plan",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-567726",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "premium-food",
      "freeze-dried-food",
      "stella-&-chewy's"
    ]
  },
  {
    "sku": "chewy-98911",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "merrick",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-639406",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "premium-food",
      "freeze-dried-food",
      "purebites",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-235070",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "wet-food",
      "adult",
      "livelong-healthy-&-strong",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "petsmart-5067364",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "purina-pro-plan"
    ]
  },
  {
    "sku": "petsmart-5158760",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "great-choice"
    ]
  },
  {
    "sku": "petsmart-5247762",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5310262",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "tiki-dog"
    ]
  },
  {
    "sku": "petsmart-5246994",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5288828",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "canidae"
    ]
  },
  {
    "sku": "petsmart-5282601",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "nature's-recipe"
    ]
  },
  {
    "sku": "petsmart-5230981",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "nutro"
    ]
  },
  {
    "sku": "petsmart-5166487",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5083856",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "veterinary-diets",
      "royal-canin-veterinary-diet"
    ]
  },
  {
    "sku": "petsmart-5281218",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "solid-gold"
    ]
  },
  {
    "sku": "petsmart-5200131",
    "tags": [
      "dog-wet-food",
      "dog",
      "food",
      "canned-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "amazon-pet-B0B42LQRYT",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "generic",
      "asin-B0B42LQRYT"
    ]
  },
  {
    "sku": "amazon-pet-B09QQD38ZY",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "birds",
      "food",
      "comtim",
      "asin-B09QQD38ZY"
    ]
  },
  {
    "sku": "amazon-pet-B0B42Q8PHN",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B42Q8PHN"
    ]
  },
  {
    "sku": "amazon-pet-B0B42NBR66",
    "tags": [
      "dog-wet-food",
      "pet-supplies",
      "birds",
      "feeding-watering-supplies",
      "generic",
      "asin-B0B42NBR66"
    ]
  },
  {
    "sku": "aliexpress-pet-01613",
    "tags": [
      "dog-wet-food",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01901",
    "tags": [
      "dog-wet-food",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01914",
    "tags": [
      "dog-wet-food",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01927",
    "tags": [
      "dog-wet-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01940",
    "tags": [
      "dog-wet-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01981",
    "tags": [
      "dog-wet-food",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-kd-with-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.2pct",
      "-",
      "original",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-ld-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.9pct",
      "-",
      "original",
      "liver-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-light-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.6pct",
      "adult",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-medium-savoury-turkey-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.5pct",
      "adult",
      "with-turkey",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-small-mini-turkey-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.2pct",
      "adult",
      "small-breed",
      "with-turkey",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-mature-adult-chicken-beef-canned-multipack",
    "tags": [
      "dog-wet-food",
      "protein-5.2pct",
      "senior",
      "with-chicken-with-beef",
      "aging-care",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-puppy-chicken-beef-canned-multipack",
    "tags": [
      "dog-wet-food",
      "protein-6.9pct",
      "puppy",
      "with-chicken-with-beef",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-chicken-turkey-beef-canned-multipack",
    "tags": [
      "dog-wet-food",
      "protein-5.8pct",
      "adult",
      "with-chicken-turkey-and-beef",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-adult-multi-benefit-plus-weight-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.9pct",
      "adult",
      "with-tender-chicken-added-vegetables",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-vetessentials-puppy-multi-benefit-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-8.7pct",
      "puppy",
      "tender-chicken",
      "puppy-care",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-digestion-small-mini-turkey-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.1pct",
      "adult",
      "small-breed",
      "with-turkey",
      "digestive-care",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-small-mini-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.6pct",
      "adult",
      "small-breed",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-jd-with-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.8pct",
      "-",
      "with-chicken",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-kd-plus-mobility-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.1pct",
      "-",
      "flavoured-with-chicken",
      "kidney-care",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-id-stress-mini-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.5pct",
      "-",
      "flavoured-with-chicken",
      "nervous-system-care-and-stress",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-metabolic-plus-mobility-canned",
    "tags": [
      "dog-wet-food",
      "protein-7.0pct",
      "-",
      "original",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-on-care-chicken-stew",
    "tags": [
      "dog-wet-food",
      "protein-6.6pct",
      "-",
      "with-chicken-added-vegetables",
      "cancer-patient-support",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-gastrointestinal-biome-with-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.1pct",
      "-",
      "with-chicken",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-derm-complete-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.9pct",
      "-",
      "original",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-feline-prescription-diet-ad-canned",
    "tags": [
      "dog-wet-food",
      "protein-12.9pct",
      "-",
      "with-chicken",
      "urgent-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-digestion-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.2pct",
      "adult",
      "with-chicken-added-vegetables",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-gastrointestinal-biome-chicken-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.4pct",
      "-",
      "with-chicken-added-carrots",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-canine-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.8pct",
      "-",
      "with-chicken-vegetables",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-canine-chicken-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.9pct",
      "-",
      "with-chicken-vegetables",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-chicken-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.6pct",
      "-",
      "with-chicken-added-vegetables",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-canine-stress-rice-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.1pct",
      "-",
      "small-breed",
      "flavoured-with-chicken-vegetables",
      "nervous-system-care-and-stress",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-dd-duck-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.1pct",
      "-",
      "duck",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-low-fat-canine-rice-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.0pct",
      "-",
      "with-chicken-vegetables",
      "digestive-care",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-cd-multicare-canine-chicken-and-vegetable-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.3pct",
      "-",
      "with-chicken-vegetables",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-zd-mini-original-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.2pct",
      "-",
      "original",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-mature-adult-7-plus-medium-savoury-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.1pct",
      "senior",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-adult-perfect-weight-with-chicken-and-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.8pct",
      "adult",
      "with-chicken-vegetables",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-plus-mobility-canine-chicken-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.5pct",
      "-",
      "with-chicken-added-vegetables",
      "kidney-care",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-formula-savoury-beef-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.8pct",
      "adult",
      "with-beef",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-rd-canned",
    "tags": [
      "dog-wet-food",
      "protein-8.4pct",
      "-",
      "original",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-cd-multicare-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.9pct",
      "-",
      "with-chicken",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-adult-medium-savoury-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.1pct",
      "adult",
      "with-chicken",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-id-turkey-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.7pct",
      "-",
      "with-turkey",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-id-low-fat-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.5pct",
      "-",
      "original",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-metabolic-original-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.8pct",
      "-",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-wd-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.7pct",
      "-",
      "with-chicken",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-prescription-diet-ud-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.2pct",
      "-",
      "original",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sp-canine-science-plan-puppy-medium-savoury-chicken-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.8pct",
      "puppy",
      "chicken",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-ve-canine-adult-with-tender-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.3pct",
      "adult",
      "with-tender-chicken-vegetables",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-zd-low-fat-hydrolyzed-soy-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.577999999999999pct",
      "-",
      "hydrolyzed-soy-recipe",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-cd-multicare-canine-chicken-and-vegetable-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.648pct",
      "-",
      "chicken-vegetable-stew",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-dd-canine-duck-formula-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.784pct",
      "-",
      "duck-formula",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-chicken-rice-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-29.9pct",
      "puppy",
      "chicken-rice-stew",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-beef-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.2700000000000005pct",
      "puppy",
      "small-breed",
      "beef-barley-entr-e",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-chicken-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-8.41pct",
      "puppy",
      "chicken-barley-entr-e",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-joint-support-vegetables-tuna-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.99pct",
      "-",
      "hearty-vegetables-and-tuna-stew",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-vegetables-salmon-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.981000000000001pct",
      "-",
      "hearty-vegetables-salmon-stew",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-salmon-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.972pct",
      "adult",
      "salmon-barley-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-healthy-cuisine-roasted-chicken-carrots-spinach-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.109999999999999pct",
      "adult",
      "roasted-chicken-carrots-spinach-stew",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-healthy-cuisine-braised-beef-carrots-peas-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.24pct",
      "adult",
      "digestive-care",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-chicken-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.774pct",
      "senior",
      "chicken-barley-entr-e",
      "musculoskeletal-and-joint-care",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-plus-mobility-canine-vegetable-and-tuna-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.9340000000000006pct",
      "-",
      "vegetable-tuna-stew",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-ud-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-13.8pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-chicken-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-16.0pct",
      "-",
      "chicken-vegetable-stew",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-beef-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-15.9pct",
      "-",
      "beef-vegetable-stew",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-with-lamb-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.366pct",
      "-",
      "with-lamb",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-jd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.096000000000001pct",
      "-",
      "with-lamb",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.611pct",
      "-",
      "with-chicken",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-dd-canine-venison-formula-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.378pct",
      "-",
      "potato-venison-recipe",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-dd-canine-salmon-formula-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.224pct",
      "-",
      "salmon-formula",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-gd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.0920000000000005pct",
      "-",
      "turkey-flavor",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-cd-multicare-low-fat-vegetables-and-turkey-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.176pct",
      "-",
      "vegetables-turkey",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-ad-canine-feline-canned",
    "tags": [
      "dog-wet-food",
      "protein-9.68pct",
      "-",
      "with-chicken",
      "urgent-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-sensitive-stomach-and-skin-salmon-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.355pct",
      "puppy",
      "salmon-vegetable-stew",
      "puppy-care",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-chicken-vegetable-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.138pct",
      "adult",
      "chicken-vegetable-entr-e",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-salmon-vegetable-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.39pct",
      "-",
      "salmon-vegetable-entr-e",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-chicken-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.592pct",
      "adult",
      "tender-chicken-vegetable-stew",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-savory-stew-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.058pct",
      "adult",
      "savory-stew-with-chicken-vegetables",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-chicken-vegetable-rice-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.112pct",
      "adult",
      "chicken-vegetable-rice-stew",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-healthy-cuisine-roasted-chicken-carrots-spinach-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.42pct",
      "senior",
      "roasted-chicken-carrots-spinach-stew",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-healthy-cuisine-braised-beef-carrots-peas-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.648pct",
      "senior",
      "hearty-beef-carrots-peas-stew",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-senior-vitality-chicken-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.3299999999999996pct",
      "senior",
      "chicken-vegetable",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-wd-canine-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.392pct",
      "-",
      "vegetable-chicken-stew",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-wd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.246pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-zd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.356pct",
      "-",
      "original-flavor",
      "digestive-care",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-kd-plus-mobility-canine-chicken-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-15.6pct",
      "-",
      "chicken-vegetable-stew",
      "kidney-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-canine-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.64pct",
      "-",
      "vegetable-chicken-stew",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-metabolic-canine-vegetable-and-beef-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.752pct",
      "-",
      "vegetable-beef-stew",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-ld-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.1579999999999995pct",
      "-",
      "chicken-flavor",
      "liver-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-canine-stress-rice-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-23.4pct",
      "-",
      "small-breed",
      "rice-vegetable-chicken-stew",
      "nervous-system-care-and-stress",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-canine-chicken-and-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.08pct",
      "-",
      "chicken-vegetables",
      "nervous-system-care-and-stress",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-low-fat-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.412pct",
      "-",
      "original-flavor",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.544pct",
      "-",
      "with-turkey",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-id-low-fat-canine-rice-vegetable-and-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-23.4pct",
      "-",
      "rice-vegetable-and-chicken-stew",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-gastrointestinal-biome-chicken-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.554pct",
      "-",
      "chicken-and-vegetable-stew",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-onc-on-care-chicken-stew",
    "tags": [
      "dog-wet-food",
      "protein-4.859999999999999pct",
      "-",
      "chicken-vegetable-stew",
      "cancer-patient-support",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-derm-complete-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.4pct",
      "-",
      "rice-egg-recipe",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-metabolic-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.1160000000000005pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-sensitive-stomach-and-skin-tender-turkey-rice-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.43pct",
      "-",
      "tender-turkey-rice-stew",
      "skin-health",
      "food-sensitivity",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-breed-chicken-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.83pct",
      "adult",
      "small-breed",
      "chicken-barley-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-small-mini-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.16pct",
      "adult",
      "small-breed",
      "chicken-vegetables-entr-e",
      "digestive-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-hearty-vegetable-chicken-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.64pct",
      "-",
      "hearty-vegetable-chicken-stew",
      "weight-management",
      "musculoskeletal-and-joint-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-turkey-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.9160000000000004pct",
      "senior",
      "turkey-barley-entr-e",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-digestion-chicken-rice-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.918pct",
      "adult",
      "chicken-rice-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-brain-care-plus-jd-rice-turkey-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.016pct",
      "-",
      "rice-turkey",
      "nervous-system-care-and-stress",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-multi-organ-turkey-vegetables-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.072pct",
      "-",
      "turkey-vegetable-stew",
      "urgent-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-zd-can",
    "tags": [
      "dog-wet-food",
      "protein-4.356pct",
      "-",
      "original-flavor",
      "food-sensitivity",
      "skin-health",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-savory-stew-beef-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.859999999999999pct",
      "senior",
      "savory-stew-with-beef-vegetables",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-mini-beef-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.17pct",
      "adult",
      "small-breed",
      "beef-barley-entr-e",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-perfect-weight-chicken-vegetable-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.138pct",
      "-",
      "chicken-vegetable-entr-e",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-small-breed-chicken-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.774pct",
      "senior",
      "small-breed",
      "chicken-barley-entr-e",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-savory-stew-with-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.7128pct",
      "puppy",
      "chicken-vegetables",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-7-plus-senior-vitality-small-breed-chicken-vegetable-stew-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.3299999999999996pct",
      "senior",
      "small-breed",
      "chicken-vegetable",
      "aging-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-savory-stew-beef-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "protein-4.698pct",
      "adult",
      "savory-stew-with-beef-vegetables",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-small-toy-stew-variety-pack-plastic-tray",
    "tags": [
      "dog-wet-food",
      "protein-4.964pct",
      "adult",
      "small-breed",
      "savory-stew-with-chicken-vegetables",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-canine-rd-can",
    "tags": [
      "dog-wet-food",
      "protein-7.348pct",
      "-",
      "chicken-flavor",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-sd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-7.5pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-hd-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-3.806pct",
      "-",
      "with-chicken",
      "heart-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-light-liver-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.236pct",
      "adult",
      "with-liver",
      "weight-management",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-savory-stew-chicken-zucchini-no-corn-wheat-soy",
    "tags": [
      "dog-wet-food",
      "protein-4.26pct",
      "adult",
      "savory-stew-with-chicken-zucchini",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-small-breed-chicken-barley-entree-canned",
    "tags": [
      "dog-wet-food",
      "protein-6.16pct",
      "puppy",
      "small-breed",
      "chicken-barley-entr-e",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-adult-savory-stew-beef-zucchini-no-corn-wheat-soy",
    "tags": [
      "dog-wet-food",
      "protein-3.795pct",
      "adult",
      "savory-stew-with-beef-zucchini",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-adult-small-toy-savory-stew-beef-vegetables-plastic-tray",
    "tags": [
      "dog-wet-food",
      "protein-4.607pct",
      "adult",
      "small-breed",
      "savory-stew-with-beef-vegetables",
      "adult-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-sd-canine-puppy-small-breed-savory-stew-chicken-vegetables-tray",
    "tags": [
      "dog-wet-food",
      "protein-5.526pct",
      "puppy",
      "small-breed",
      "savory-stew-with-chicken-vegetables",
      "puppy-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-dog-pd-cd-multicare-canine-canned",
    "tags": [
      "dog-wet-food",
      "protein-5.346pct",
      "-",
      "chicken-flavor",
      "urinary-care",
      "hills",
      "prescription-diet",
      "veterinary"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-ld-canned",
    "tags": [
      "dog-wet-food",
      "liver-care",
      "adult",
      "small-breed--medium-breed--large-breed-breed",
      "original",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-adult-light-canned",
    "tags": [
      "dog-wet-food",
      "adult",
      "small-breed--medium-breed--large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-medium-savoury-turkey-canned",
    "tags": [
      "dog-wet-food",
      "adult",
      "small-breed--medium-breed--large-breed-breed",
      "with-turkey",
      "hills"
    ]
  },
  {
    "sku": "hills-sd-canine-adult-perfect-weight-small-mini-turkey-canned",
    "tags": [
      "dog-wet-food",
      "small-mini-adult-dog-1-",
      "adult",
      "small-breed-breed",
      "with-turkey",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-mature-adult-chicken-beef-canned-multipack",
    "tags": [
      "dog-wet-food",
      "mature-adult-dog-7-",
      "senior",
      "small-breed--medium-breed--large-breed-breed",
      "with-chicken-with-beef",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-puppy-chicken-beef-canned-multipack",
    "tags": [
      "dog-wet-food",
      "puppy-1",
      "puppy-pregnant-nursing",
      "small-breed--medium-breed--large-breed-breed",
      "with-chicken-with-beef",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-adult-chicken-turkey-beef-canned-multipack",
    "tags": [
      "dog-wet-food",
      "adult-1-6",
      "adult",
      "medium-breed--large-breed-breed",
      "with-chicken-turkey-and-beef",
      "hills"
    ]
  },
  {
    "sku": "hills-ve-canine-vetessentials-adult-multi-benefit-plus-weight-chicken-vegetables-canned",
    "tags": [
      "dog-wet-food",
      "neutered-sterilised",
      "healthy-weight",
      "small-breed--medium-breed--large-breed-breed",
      "with-tender-chicken-added-vegetables",
      "hills"
    ]
  },
  {
    "sku": "hills-ve-canine-vetessentials-puppy-multi-benefit-chicken-canned",
    "tags": [
      "dog-wet-food",
      "puppy",
      "puppy-pregnant-nursing",
      "medium-breed--small-breed-breed",
      "tender-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-adult-perfect-digestion-small-mini-turkey-canned",
    "tags": [
      "dog-wet-food",
      "small-mini-adult-dog-1-6",
      "adult--senior",
      "small-breed-breed",
      "with-turkey",
      "hills"
    ]
  },
  {
    "sku": "hills-sp-canine-science-plan-adult-small-mini-chicken-canned",
    "tags": [
      "dog-wet-food",
      "small-mini-adult-dog-1-6",
      "adult",
      "small-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-prescription-diet-jd-with-chicken-canned",
    "tags": [
      "dog-wet-food",
      "joint-care",
      "adult--senior",
      "small-breed--medium-breed--large-breed-breed",
      "with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-kd-plus-mobility-chicken-canned",
    "tags": [
      "dog-wet-food",
      "kidney-care",
      "joint-care",
      "adult--senior",
      "large-breed--medium-breed--small-breed-breed",
      "flavoured-with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-id-stress-mini-chicken-canned",
    "tags": [
      "dog-wet-food",
      "digestive-care",
      "adult--senior",
      "small-breed-breed",
      "flavoured-with-chicken",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-metabolic-plus-mobility-canned",
    "tags": [
      "dog-wet-food",
      "weight-management",
      "joint-care",
      "adult--senior",
      "small-breed--medium-breed--large-breed-breed",
      "original",
      "hills"
    ]
  },
  {
    "sku": "hills-pd-canine-on-care-chicken-stew",
    "tags": [
      "dog-wet-food",
      "restorative-care",
      "adult--senior",
      "with-chicken-added-vegetables",
      "hills"
    ]
  }
];

export default entries;