// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-accessory  |  Products with image: 139 (15 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-286322",
    "tags": [
      "dog-accessory",
      "cat",
      "leashes-collars-harnesses",
      "id-tags-accessories",
      "quick-tag"
    ]
  },
  {
    "sku": "chewy-311969",
    "tags": [
      "dog-accessory",
      "cat",
      "bowls-feeders",
      "bowls-dishes",
      "frisco"
    ]
  },
  {
    "sku": "chewy-367681",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-potty",
      "poop-bags-scoopers",
      "poop-bags",
      "wild-one",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-252287",
    "tags": [
      "dog-accessory",
      "dog",
      "beds",
      "pillow-beds",
      "b&g-martin"
    ]
  },
  {
    "sku": "chewy-648694",
    "tags": [
      "dog-accessory",
      "dog",
      "leashes-collars-harnesses",
      "collars",
      "standard",
      "sublime"
    ]
  },
  {
    "sku": "chewy-363994",
    "tags": [
      "dog-accessory",
      "dog",
      "carriers-travel",
      "travel-bowls-bags",
      "dexas-popware-for-pets"
    ]
  },
  {
    "sku": "chewy-198272",
    "tags": [
      "dog-accessory",
      "dog",
      "treats",
      "soft-chewy-treats",
      "smart-cookie-barkery",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-283994",
    "tags": [
      "dog-accessory",
      "cat",
      "clothing-accessories",
      "shirts-dresses",
      "littlearth"
    ]
  },
  {
    "sku": "chewy-151489",
    "tags": [
      "dog-accessory",
      "dog",
      "treats",
      "bones-bully-sticks-natural-chews",
      "hard-chews",
      "emerald-pet",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-263774",
    "tags": [
      "dog-accessory",
      "dog",
      "gifts-books",
      "home-goods",
      "doormats",
      "bungalow-flooring"
    ]
  },
  {
    "sku": "chewy-237008",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-potty",
      "poop-bags-scoopers",
      "poop-bags",
      "frisco"
    ]
  },
  {
    "sku": "chewy-358475",
    "tags": [
      "dog-accessory",
      "cat",
      "clothing-accessories",
      "accessories",
      "hats",
      "frisco"
    ]
  },
  {
    "sku": "chewy-641502",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-potty",
      "poop-bags-scoopers",
      "poop-bag-holders",
      "poopshark"
    ]
  },
  {
    "sku": "chewy-256759",
    "tags": [
      "dog-accessory",
      "dog",
      "leashes-collars-harnesses",
      "leashes",
      "standard",
      "frisco"
    ]
  },
  {
    "sku": "petsmart-5132508",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "fence-systems",
      "high-tech-pet"
    ]
  },
  {
    "sku": "petsmart-5118873",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "dog-doors-and-gates",
      "carlson-pet-products"
    ]
  },
  {
    "sku": "petsmart-5307432",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "leashes",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5292391",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "cooling-and-heating-beds",
      "creative-solutions"
    ]
  },
  {
    "sku": "petsmart-5303622",
    "tags": [
      "dog-accessory",
      "dog",
      "training-and-behavior",
      "potty-training",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5325780",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5136626",
    "tags": [
      "dog-accessory",
      "dog",
      "training-and-behavior",
      "bark-control",
      "petsafe"
    ]
  },
  {
    "sku": "petsmart-5306392",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "dog-doors-and-gates",
      "cardinal-gates"
    ]
  },
  {
    "sku": "petsmart-5320572",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "dog-doors-and-gates",
      "high-tech-pet"
    ]
  },
  {
    "sku": "petsmart-5330088",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first-dallas-stars-tee-71713-html",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5270153",
    "tags": [
      "dog-accessory",
      "dog",
      "training-and-behavior",
      "bark-control",
      "petsafe"
    ]
  },
  {
    "sku": "petsmart-5298642",
    "tags": [
      "dog-accessory",
      "dog",
      "grooming-supplies",
      "hair-clippers-and-trimmers",
      "andis"
    ]
  },
  {
    "sku": "petsmart-5167118",
    "tags": [
      "dog-accessory",
      "dog",
      "treats",
      "biscuits-and-bakery",
      "old-mother-hubbard"
    ]
  },
  {
    "sku": "petsmart-5330337",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "sweaters-and-coats",
      "fresh-pawz"
    ]
  },
  {
    "sku": "petsmart-5233980",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5310344",
    "tags": [
      "dog-accessory",
      "dog",
      "grooming-supplies",
      "wipes-and-deodorizers",
      "wet-ones"
    ]
  },
  {
    "sku": "petsmart-5244689",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5289792",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "cuddler-beds",
      "snoozer"
    ]
  },
  {
    "sku": "petsmart-5275270",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5289453",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "cuddler-beds",
      "pendleton"
    ]
  },
  {
    "sku": "petsmart-5328100",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "bandanas-bows-and-hats",
      "top-paw-green-backpack-70879-html",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5258938",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5297147",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "blankets",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5326003",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5325991",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "leashes",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5244681",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5258801",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5307605",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5311703",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-supplies",
      "waste-disposal",
      "barkyard"
    ]
  },
  {
    "sku": "petsmart-5325247",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "pillow-beds",
      "pendleton"
    ]
  },
  {
    "sku": "petsmart-5322504",
    "tags": [
      "dog-accessory",
      "dog",
      "treats",
      "bones-and-rawhide",
      "collachews"
    ]
  },
  {
    "sku": "petsmart-5252459",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5152514",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "ramps-and-steps",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5323730",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "harnesses",
      "kong"
    ]
  },
  {
    "sku": "petsmart-5217859",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "florida-gators-ncaa-jersey-23335-html",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5302897",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "cuddler-beds",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5271011",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5300853",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "id-tags",
      "tagworks"
    ]
  },
  {
    "sku": "petsmart-5258278",
    "tags": [
      "dog-accessory",
      "dog",
      "grooming-supplies",
      "shampoos-and-conditioners",
      "burt's-bees"
    ]
  },
  {
    "sku": "petsmart-5153917",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "carriers-and-crates",
      "pet-gear"
    ]
  },
  {
    "sku": "petsmart-5306990",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "blankets",
      "e&amp;s-pets"
    ]
  },
  {
    "sku": "petsmart-5325045",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pendleton"
    ]
  },
  {
    "sku": "petsmart-5294176",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-supplies",
      "stain-and-odor-removers",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5155190",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-supplies",
      "furniture-and-car-protection",
      "kurgo-wander-pet-hammock-7527-html",
      "kurgo"
    ]
  },
  {
    "sku": "petsmart-5270900",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5252223",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5314260",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "bandanas-bows-and-hats",
      "buttons-and-bones"
    ]
  },
  {
    "sku": "petsmart-5227698",
    "tags": [
      "dog-accessory",
      "dog",
      "bowls-and-feeders",
      "placemats",
      "drymate"
    ]
  },
  {
    "sku": "petsmart-5325241",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "harnesses",
      "lucy-&amp;-co."
    ]
  },
  {
    "sku": "petsmart-5245271",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5325162",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "bandanas-bows-and-hats",
      "netflix"
    ]
  },
  {
    "sku": "petsmart-5245229",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5218003",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5323476",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-supplies",
      "waste-disposal",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5242458",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5330160",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "bandanas-bows-and-hats",
      "fresh-pawz"
    ]
  },
  {
    "sku": "petsmart-5318729",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "harnesses",
      "puppia"
    ]
  },
  {
    "sku": "petsmart-5005401",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "fence-systems",
      "petsafe"
    ]
  },
  {
    "sku": "petsmart-5153301",
    "tags": [
      "dog-accessory",
      "dog",
      "bowls-and-feeders",
      "automatic-feeders",
      "petsafe"
    ]
  },
  {
    "sku": "petsmart-5259050",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5267427",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "harnesses",
      "puppia"
    ]
  },
  {
    "sku": "petsmart-5296421",
    "tags": [
      "dog-accessory",
      "dog",
      "grooming-supplies",
      "shampoos-and-conditioners",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5307440",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "leashes",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5296149",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "harnesses",
      "arcadia-trail"
    ]
  },
  {
    "sku": "petsmart-5321216",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "pillow-beds",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5188043",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-supplies",
      "furniture-and-car-protection",
      "kurgo-car-door-guard-7525-html",
      "kurgo"
    ]
  },
  {
    "sku": "petsmart-5311702",
    "tags": [
      "dog-accessory",
      "dog",
      "cleaning-supplies",
      "waste-disposal",
      "barkyard"
    ]
  },
  {
    "sku": "petsmart-5313199",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "backpacks",
      "mobile-dog-gear"
    ]
  },
  {
    "sku": "petsmart-5252322",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "texas-rangers-mlb-hoody-tee-36834-html",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5312940",
    "tags": [
      "dog-accessory",
      "dog",
      "bowls-and-feeders",
      "placemats",
      "bungalow-flooring"
    ]
  },
  {
    "sku": "petsmart-5302723",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "pillow-beds",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5321283",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "sweaters-and-coats",
      "grayson-pup"
    ]
  },
  {
    "sku": "petsmart-5311609",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "pillow-beds",
      "armarkat"
    ]
  },
  {
    "sku": "petsmart-5193615",
    "tags": [
      "dog-accessory",
      "dog",
      "bowls-and-feeders",
      "automatic-feeders",
      "pioneer-pet"
    ]
  },
  {
    "sku": "petsmart-5319368",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "cuddler-beds",
      "value-beds"
    ]
  },
  {
    "sku": "petsmart-5298633",
    "tags": [
      "dog-accessory",
      "dog",
      "beds-and-furniture",
      "cuddler-beds",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5258907",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5197044",
    "tags": [
      "dog-accessory",
      "dog",
      "crates-gates-and-containment",
      "fence-systems",
      "high-tech-pet"
    ]
  },
  {
    "sku": "petsmart-5330885",
    "tags": [
      "dog-accessory",
      "cat",
      "beds-and-furniture",
      "covered-beds",
      "best-friends-by-sheri"
    ]
  },
  {
    "sku": "petsmart-5243705",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5325091",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "leashes",
      "pendleton"
    ]
  },
  {
    "sku": "petsmart-5244501",
    "tags": [
      "dog-accessory",
      "dog",
      "clothing-and-shoes",
      "jerseys-and-team-sports",
      "detroit-lions-nfl-team-tee-32942-html",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5263223",
    "tags": [
      "dog-accessory",
      "dog",
      "collars-harnesses-and-leashes",
      "collars",
      "top-paw-paw-dog-collar-42446-html",
      "top-paw"
    ]
  },
  {
    "sku": "amazon-pet-B096NVYKX5",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "carriers-strollers",
      "strollers",
      "noodoky",
      "asin-B096NVYKX5"
    ]
  },
  {
    "sku": "amazon-pet-B01MXGS623",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "yellow-dog-design",
      "asin-B01MXGS623"
    ]
  },
  {
    "sku": "amazon-pet-B09VC7KB9V",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "bestchong",
      "asin-B09VC7KB9V"
    ]
  },
  {
    "sku": "amazon-pet-B0B1DBFXLF",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "generic",
      "asin-B0B1DBFXLF"
    ]
  },
  {
    "sku": "amazon-pet-B09HQVSX5W",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "woofy",
      "asin-B09HQVSX5W"
    ]
  },
  {
    "sku": "amazon-pet-B08VP293SC",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "tanniyo",
      "asin-B08VP293SC"
    ]
  },
  {
    "sku": "amazon-pet-B0B4ZF1MWH",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "erhu",
      "asin-B0B4ZF1MWH"
    ]
  },
  {
    "sku": "amazon-pet-B0B4S2R5PF",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "maxbell",
      "asin-B0B4S2R5PF"
    ]
  },
  {
    "sku": "amazon-pet-B09MNJPRJ9",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "treats",
      "snacks",
      "pawfect-treats",
      "asin-B09MNJPRJ9"
    ]
  },
  {
    "sku": "amazon-pet-B09HJHQFMG",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "harnesses",
      "puppia",
      "asin-B09HJHQFMG"
    ]
  },
  {
    "sku": "amazon-pet-B07D4LCMLP",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "petsmaker",
      "asin-B07D4LCMLP"
    ]
  },
  {
    "sku": "amazon-pet-B09VC7W3HS",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "bestchong",
      "asin-B09VC7W3HS"
    ]
  },
  {
    "sku": "amazon-pet-B09L8NTMF4",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "birds'-park",
      "asin-B09L8NTMF4"
    ]
  },
  {
    "sku": "amazon-pet-B09VGB1PB4",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "macos",
      "asin-B09VGB1PB4"
    ]
  },
  {
    "sku": "amazon-pet-B001CQZ1KU",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "beds",
      "midwest-homes-for-pets",
      "asin-B001CQZ1KU"
    ]
  },
  {
    "sku": "amazon-pet-B07TBQ8YJ8",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "carriers-strollers",
      "strollers",
      "roodo",
      "asin-B07TBQ8YJ8"
    ]
  },
  {
    "sku": "amazon-pet-B0B4S4D6XT",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "maxbell",
      "asin-B0B4S4D6XT"
    ]
  },
  {
    "sku": "amazon-pet-B0B6ZSRLT6",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "maxbell",
      "asin-B0B6ZSRLT6"
    ]
  },
  {
    "sku": "amazon-pet-B09TDWFJ45",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "dogs",
      "apparel-accessories",
      "dresses",
      "visit-the-kutkut-store",
      "asin-B09TDWFJ45"
    ]
  },
  {
    "sku": "amazon-pet-B01N07AOBT",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "dogs",
      "collars-harnesses-leashes",
      "harnesses",
      "basic-halter-harnesses",
      "yellow-dog-design",
      "asin-B01N07AOBT"
    ]
  },
  {
    "sku": "amazon-pet-B09Y8WWMTD",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "generic",
      "asin-B09Y8WWMTD"
    ]
  },
  {
    "sku": "amazon-pet-B08VNY6PJV",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "visit-the-the-dds-store-store",
      "asin-B08VNY6PJV"
    ]
  },
  {
    "sku": "amazon-pet-B07D4KWYN6",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "petsmaker",
      "asin-B07D4KWYN6"
    ]
  },
  {
    "sku": "amazon-pet-B09GS2QK2W",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "visit-the-rvpaws-store",
      "asin-B09GS2QK2W"
    ]
  },
  {
    "sku": "amazon-pet-B0788QTV62",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "dogs",
      "carriers-travel-products",
      "backpacks",
      "cloverpet",
      "asin-B0788QTV62"
    ]
  },
  {
    "sku": "amazon-pet-B08V1B3H1W",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "generic",
      "asin-B08V1B3H1W"
    ]
  },
  {
    "sku": "amazon-pet-B07B4Y89C1",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "beds",
      "visit-the-hiputee-store",
      "asin-B07B4Y89C1"
    ]
  },
  {
    "sku": "amazon-pet-B099KM3Z9C",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "sutinna",
      "asin-B099KM3Z9C"
    ]
  },
  {
    "sku": "amazon-pet-B0B1D79X6V",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "generic",
      "asin-B0B1D79X6V"
    ]
  },
  {
    "sku": "amazon-pet-B09VC7JYCK",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "bestchong",
      "asin-B09VC7JYCK"
    ]
  },
  {
    "sku": "amazon-pet-B0B4HMFC24",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "rongm",
      "asin-B0B4HMFC24"
    ]
  },
  {
    "sku": "amazon-pet-B09VC83NL7",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "bestchong",
      "asin-B09VC83NL7"
    ]
  },
  {
    "sku": "amazon-pet-B091Y31HJT",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "ovida",
      "asin-B091Y31HJT"
    ]
  },
  {
    "sku": "amazon-pet-B0B6W4HNGD",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "generic",
      "asin-B0B6W4HNGD"
    ]
  },
  {
    "sku": "amazon-pet-B08TZRQYDF",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "generic",
      "asin-B08TZRQYDF"
    ]
  },
  {
    "sku": "amazon-pet-B07MJX795R",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-blankets",
      "visit-the-kozi-pet-store",
      "asin-B07MJX795R"
    ]
  },
  {
    "sku": "amazon-pet-B0B1D8PVG5",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "generic",
      "asin-B0B1D8PVG5"
    ]
  },
  {
    "sku": "amazon-pet-B07D4LDRWB",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "petsmaker",
      "asin-B07D4LDRWB"
    ]
  },
  {
    "sku": "amazon-pet-B0B4S8BYF1",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "generic",
      "asin-B0B4S8BYF1"
    ]
  },
  {
    "sku": "amazon-pet-B07KJRZRT3",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-blankets",
      "petami",
      "asin-B07KJRZRT3"
    ]
  },
  {
    "sku": "amazon-pet-B09HS85M2W",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "vms-india",
      "asin-B09HS85M2W"
    ]
  },
  {
    "sku": "amazon-pet-B09VC78K2X",
    "tags": [
      "dog-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "bestchong",
      "asin-B09VC78K2X"
    ]
  }
];

export default entries;