// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-toy  |  Products: 226

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-144968",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "discs",
      "hyper-pet"
    ]
  },
  {
    "sku": "chewy-155129",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "unstuffed-toys",
      "mighty"
    ]
  },
  {
    "sku": "chewy-71362",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "stuffed-toys",
      "ethical-pet"
    ]
  },
  {
    "sku": "chewy-221055",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "stuffed-toys",
      "marvel"
    ]
  },
  {
    "sku": "chewy-267852",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "rope-tug-toys",
      "marvel"
    ]
  },
  {
    "sku": "chewy-315820",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "discs",
      "herodog"
    ]
  },
  {
    "sku": "chewy-735806",
    "tags": [
      "dog-toy",
      "dog",
      "beds",
      "bolster-beds",
      "pets-first"
    ]
  },
  {
    "sku": "chewy-245811",
    "tags": [
      "dog-toy",
      "cat",
      "grooming",
      "grooming-tools",
      "kenchii"
    ]
  },
  {
    "sku": "chewy-222514",
    "tags": [
      "dog-toy",
      "dog",
      "beds",
      "bolster-beds",
      "furhaven"
    ]
  },
  {
    "sku": "chewy-62012",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "unstuffed-toys",
      "petstages"
    ]
  },
  {
    "sku": "chewy-82848",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "balls",
      "hartz"
    ]
  },
  {
    "sku": "chewy-248319",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "stuffed-toys",
      "hugglehounds"
    ]
  },
  {
    "sku": "chewy-361434",
    "tags": [
      "dog-toy",
      "dog",
      "cleaning-potty",
      "poop-bags-scoopers",
      "poop-bags",
      "doggy-do-good"
    ]
  },
  {
    "sku": "chewy-269115",
    "tags": [
      "dog-toy",
      "cat",
      "leashes-collars-harnesses",
      "id-tags-accessories",
      "quick-tag"
    ]
  },
  {
    "sku": "petsmart-5308133",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5327517",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5300089",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5327453",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5305745",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5323969",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "joyhound"
    ]
  },
  {
    "sku": "petsmart-5243938",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5233933",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5308327",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "chuckit!"
    ]
  },
  {
    "sku": "petsmart-5310627",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "thrills-&amp;-chills"
    ]
  },
  {
    "sku": "petsmart-5327451",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5305766",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "pets-first"
    ]
  },
  {
    "sku": "petsmart-5325000",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "netflix"
    ]
  },
  {
    "sku": "petsmart-5308496",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "nerf-dog"
    ]
  },
  {
    "sku": "petsmart-5308281",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "fetch-toys",
      "kong"
    ]
  },
  {
    "sku": "petsmart-5308132",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "plush-toys",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5147120",
    "tags": [
      "dog-toy",
      "dog",
      "toys",
      "rope-and-tug-toys",
      "kong"
    ]
  },
  {
    "sku": "amazon-pet-B09TH4F4TV",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "ubersweet",
      "asin-B09TH4F4TV"
    ]
  },
  {
    "sku": "amazon-pet-B0993M5LLL",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "catnip-toys",
      "kapoor-pets",
      "asin-B0993M5LLL"
    ]
  },
  {
    "sku": "amazon-pet-B095N4JCG8",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-blankets",
      "visit-the-petslover-store",
      "asin-B095N4JCG8"
    ]
  },
  {
    "sku": "amazon-pet-B06XXZCZ5F",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "joyelf",
      "asin-B06XXZCZ5F"
    ]
  },
  {
    "sku": "amazon-pet-B09KRSM8DD",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "ubersweet",
      "asin-B09KRSM8DD"
    ]
  },
  {
    "sku": "amazon-pet-B09L77VYDS",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "bedding",
      "bed-mats",
      "fabater",
      "asin-B09L77VYDS"
    ]
  },
  {
    "sku": "amazon-pet-B07DQ5DZB9",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "beds",
      "bessie-and-barnie",
      "asin-B07DQ5DZB9"
    ]
  },
  {
    "sku": "amazon-pet-B09C5HLCQQ",
    "tags": [
      "dog-toy",
      "pet-supplies",
      "cats",
      "toys",
      "interactive-toys",
      "dog-trust",
      "asin-B09C5HLCQQ"
    ]
  },
  {
    "sku": "aliexpress-pet-00031",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00040",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00041",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00052",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00057",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00085",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00099",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00105",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00112",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00113",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00114",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00124",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00146",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00152",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00163",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00176",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00183",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00188",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00191",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00204",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00205",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00219",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00221",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00243",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00259",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00261",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00290",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00299",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00304",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00327",
    "tags": [
      "dog-toy",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00330",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00372",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00393",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00397",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00408",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00411",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00437",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00442",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00468",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00501",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00505",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00529",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00530",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00538",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00540",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00546",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00554",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00556",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00565",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00583",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00608",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00619",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00626",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00634",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00658",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00669",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00671",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00685",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00693",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00706",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00736",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00740",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00747",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00759",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00760",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00762",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00770",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00794",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00797",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00802",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00804",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00810",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00818",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00827",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00831",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00832",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00837",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00839",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00844",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00845",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00849",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00876",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-00879",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00895",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00902",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00904",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00915",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00918",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00948",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00954",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00956",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00958",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00977",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00992",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01000",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01037",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01044",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01053",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01068",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01074",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-01098",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01099",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01100",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01134",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01135",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01142",
    "tags": [
      "dog-toy",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01156",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01218",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01219",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01228",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01237",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01240",
    "tags": [
      "dog-toy",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01242",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01252",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01271",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01272",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01282",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01288",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01289",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-01290",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01295",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01299",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01311",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01319",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01338",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01349",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01392",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01394",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01398",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01406",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01420",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01442",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01450",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01451",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01456",
    "tags": [
      "dog-toy"
    ]
  },
  {
    "sku": "aliexpress-pet-01458",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01459",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01529",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01531",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01545",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01560",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01567",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01577",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01578",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01584",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01595",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01598",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01622",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01637",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01638",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01640",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01643",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01644",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01650",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01659",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01671",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01680",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01700",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01704",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01719",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01725",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01726",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01737",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01739",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01763",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01771",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01772",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01786",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01809",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01819",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01840",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01850",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01872",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01874",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01890",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01908",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01916",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01926",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01930",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01932",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01950",
    "tags": [
      "dog-toy",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01953",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01958",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01966",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01976",
    "tags": [
      "dog-toy",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01982",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01995",
    "tags": [
      "dog-toy",
      "popular",
      "best-seller",
      "in-stock"
    ]
  }
];

export default entries;