// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: dog-dry-food  |  Products with image: 33 (227 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-52719",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "hill's-science-diet",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-733462",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "high-protein",
      "blue-buffalo",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-213621",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "high-protein",
      "american-journey",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-93046",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "victor",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-295188",
    "tags": [
      "dog-dry-food",
      "dog",
      "carriers-travel",
      "travel-bowls-bags",
      "mobile-dog-gear"
    ]
  },
  {
    "sku": "chewy-267891",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "premium-food",
      "acana",
      "has-ingredients",
      "has-nutrition",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-318128",
    "tags": [
      "dog-dry-food",
      "dog",
      "toys",
      "interactive-toys",
      "treat-toys-dispensers",
      "hanamya"
    ]
  },
  {
    "sku": "chewy-it’s an easy way to pack your pooch’s diet with nutrients",
    "tags": [
      "dog-dry-food",
      "'https://image.chewy.com/is/image/catalog/567726_pt1._ac_ss500_v1657659988_.jpg'"
    ]
  },
  {
    "sku": "petsmart-5329365",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "chicken-soup-for-the-soul"
    ]
  },
  {
    "sku": "petsmart-5266326",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "food-toppers",
      "wellness"
    ]
  },
  {
    "sku": "petsmart-5209448",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5314875",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "veterinary-diets",
      "blue-buffalo-natural-veterinary-diet"
    ]
  },
  {
    "sku": "petsmart-5180506",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "purina-one"
    ]
  },
  {
    "sku": "petsmart-5299403",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5248205",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "instinct"
    ]
  },
  {
    "sku": "petsmart-5177228",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "nature's-recipe"
    ]
  },
  {
    "sku": "petsmart-5278690",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "authority"
    ]
  },
  {
    "sku": "petsmart-5171472",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "wellness"
    ]
  },
  {
    "sku": "petsmart-5128755",
    "tags": [
      "dog-dry-food",
      "dog",
      "bowls-and-feeders",
      "food-and-water-bowls",
      "top-paw"
    ]
  },
  {
    "sku": "petsmart-5306544",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5162673",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "blue-buffalo"
    ]
  },
  {
    "sku": "petsmart-5313092",
    "tags": [
      "dog-dry-food",
      "dog",
      "bowls-and-feeders",
      "food-and-water-bowls",
      "mobile-dog-gear"
    ]
  },
  {
    "sku": "petsmart-5182763",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "hill's-science-diet"
    ]
  },
  {
    "sku": "petsmart-5258015",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "veterinary-diets",
      "purina-pro-plan-veterinary-diets"
    ]
  },
  {
    "sku": "petsmart-5329695",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "nutro-max"
    ]
  },
  {
    "sku": "petsmart-5306037",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "instinct"
    ]
  },
  {
    "sku": "petsmart-5301407",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "only-natural-pet"
    ]
  },
  {
    "sku": "petsmart-5299392",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "petsmart-5299381",
    "tags": [
      "dog-dry-food",
      "dog",
      "food",
      "dry-food",
      "merrick"
    ]
  },
  {
    "sku": "amazon-pet-B08T7H2JPY",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B08T7H2JPY"
    ]
  },
  {
    "sku": "amazon-pet-B09FZ7MMTW",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "woofy",
      "asin-B09FZ7MMTW"
    ]
  },
  {
    "sku": "amazon-pet-B0B42MDFF5",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "cats",
      "food",
      "dry",
      "generic",
      "asin-B0B42MDFF5"
    ]
  },
  {
    "sku": "amazon-pet-B08T74ZSLC",
    "tags": [
      "dog-dry-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B08T74ZSLC"
    ]
  }
];

export default entries;