// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: fish-food  |  Products with image: 10 (1 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "petsmart-5300528",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "food",
      "fluval"
    ]
  },
  {
    "sku": "petsmart-5220040",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "salt-water-aquarium-care",
      "api-marine-stress-zyme-23666-html",
      "api"
    ]
  },
  {
    "sku": "petsmart-5272279",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "water-care-and-conditioning",
      "kent-marine"
    ]
  },
  {
    "sku": "petsmart-5160269",
    "tags": [
      "fish-food",
      "reptile",
      "food",
      "zoo-med"
    ]
  },
  {
    "sku": "petsmart-5016501",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "disease-treatment",
      "tetra-aquarium-ick-guard-18095-html",
      "tetra"
    ]
  },
  {
    "sku": "petsmart-5292835",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "pond-care",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5131378",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "salt-water-aquarium-care",
      "api-marine-melafix-25991-html",
      "api"
    ]
  },
  {
    "sku": "petsmart-5169406",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "pond-care",
      "tetra-pond-tubing-16361-html",
      "tetra"
    ]
  },
  {
    "sku": "petsmart-5272821",
    "tags": [
      "fish-food",
      "fish",
      "food-and-care",
      "food",
      "ocean-nutrition"
    ]
  },
  {
    "sku": "amazon-pet-B097MRGGPX",
    "tags": [
      "fish-food",
      "pet-supplies",
      "small-animals",
      "food",
      "feedme",
      "asin-B097MRGGPX"
    ]
  }
];

export default entries;