// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: fish-accessory  |  Products: 52

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-141736",
    "tags": [
      "fish-accessory",
      "fish",
      "heaters-thermometers",
      "aquatop"
    ]
  },
  {
    "sku": "chewy-365036",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "pond-shop",
      "aquascape"
    ]
  },
  {
    "sku": "chewy-315982",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "saltwater-fish-shop",
      "underwater-treasures"
    ]
  },
  {
    "sku": "chewy-103786",
    "tags": [
      "fish-accessory",
      "reptile",
      "d-cor-accessories",
      "accessories",
      "penn-plax"
    ]
  },
  {
    "sku": "chewy-237531",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-media",
      "filter-parts-accessories",
      "simplicity"
    ]
  },
  {
    "sku": "chewy-237364",
    "tags": [
      "fish-accessory",
      "fish",
      "lighting",
      "light-fixtures",
      "let-lighting"
    ]
  },
  {
    "sku": "chewy-129816",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "saltwater-fish-shop",
      "sporn"
    ]
  },
  {
    "sku": "chewy-563374",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "pond-shop",
      "underwater-treasures"
    ]
  },
  {
    "sku": "chewy-164345",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "pond-shop",
      "tetra"
    ]
  },
  {
    "sku": "chewy-252188",
    "tags": [
      "fish-accessory",
      "fish",
      "water-care",
      "water-conditioners",
      "biorb"
    ]
  },
  {
    "sku": "chewy-562766",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "pond-shop",
      "underwater-treasures"
    ]
  },
  {
    "sku": "chewy-235456",
    "tags": [
      "fish-accessory",
      "small-pet",
      "shop-by-small-pet",
      "hamster",
      "cages-habitats",
      "playpens-habitats",
      "ware"
    ]
  },
  {
    "sku": "chewy-231192",
    "tags": [
      "fish-accessory",
      "reptile",
      "shop-by-reptile",
      "turtle",
      "zoo-med"
    ]
  },
  {
    "sku": "chewy-365083",
    "tags": [
      "fish-accessory",
      "fish",
      "shop-by-fish-type",
      "pond-shop",
      "aquascape"
    ]
  },
  {
    "sku": "petsmart-5295111",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5300957",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5314241",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "backgrounds",
      "merry-&amp;-bright"
    ]
  },
  {
    "sku": "petsmart-5291946",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5254803",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "artificial-plants",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5285597",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5188215",
    "tags": [
      "fish-accessory",
      "fish",
      "tanks-aquariums-and-nets",
      "aquariums",
      "clear-for-life"
    ]
  },
  {
    "sku": "petsmart-5272653",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "filter-media",
      "seachem"
    ]
  },
  {
    "sku": "petsmart-5180698",
    "tags": [
      "fish-accessory",
      "fish",
      "tanks-aquariums-and-nets",
      "aquarium-stands",
      "aqueon"
    ]
  },
  {
    "sku": "petsmart-5109961",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5295371",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5309696",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5188229",
    "tags": [
      "fish-accessory",
      "fish",
      "tanks-aquariums-and-nets",
      "aquariums",
      "clear-for-life"
    ]
  },
  {
    "sku": "petsmart-5282508",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "filters",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5325124",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "gravel-sand-and-stones",
      "aqua-natural"
    ]
  },
  {
    "sku": "petsmart-4033115",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "live-plants",
      "moneywort-15146-html",
      "petsmart"
    ]
  },
  {
    "sku": "petsmart-5011541",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "filter-media",
      "fluval"
    ]
  },
  {
    "sku": "petsmart-5291953",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5275826",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "artificial-plants",
      "biorb"
    ]
  },
  {
    "sku": "petsmart-5334239",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "artificial-plants",
      "biorb"
    ]
  },
  {
    "sku": "petsmart-5324063",
    "tags": [
      "fish-accessory",
      "fish",
      "live-fish",
      "goldfish-betta-and-more",
      "chocolate-shrimp-70101-html",
      "null"
    ]
  },
  {
    "sku": "petsmart-5295569",
    "tags": [
      "fish-accessory",
      "fish",
      "heating-and-lighting",
      "lights",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5188222",
    "tags": [
      "fish-accessory",
      "fish",
      "tanks-aquariums-and-nets",
      "aquariums",
      "clear-for-life"
    ]
  },
  {
    "sku": "petsmart-5301183",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "filters",
      "marineland"
    ]
  },
  {
    "sku": "petsmart-5119337",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "artificial-plants",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5285604",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "artificial-plants",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-4031697",
    "tags": [
      "fish-accessory",
      "fish",
      "live-fish",
      "goldfish-betta-and-more",
      "black-moor-goldfish-15238-html",
      "null"
    ]
  },
  {
    "sku": "petsmart-5291863",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "air-and-water-pumps",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5174441",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "backgrounds",
      "marina"
    ]
  },
  {
    "sku": "petsmart-5335307",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "biorb"
    ]
  },
  {
    "sku": "petsmart-5074025",
    "tags": [
      "fish-accessory",
      "fish",
      "tanks-aquariums-and-nets",
      "aquariums",
      "north-american-pet-products"
    ]
  },
  {
    "sku": "petsmart-5082033",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "gravel-sand-and-stones",
      "caribsea"
    ]
  },
  {
    "sku": "petsmart-5094904",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "replacement-parts",
      "marineland"
    ]
  },
  {
    "sku": "petsmart-5265081",
    "tags": [
      "fish-accessory",
      "fish",
      "starter-kits",
      "biorb"
    ]
  },
  {
    "sku": "petsmart-5119416",
    "tags": [
      "fish-accessory",
      "fish",
      "filters-and-pumps",
      "filters",
      "marineland"
    ]
  },
  {
    "sku": "petsmart-5286468",
    "tags": [
      "fish-accessory",
      "fish",
      "decor-gravel-and-substrate",
      "ornaments",
      "top-fin"
    ]
  },
  {
    "sku": "petsmart-5188203",
    "tags": [
      "fish-accessory",
      "fish",
      "tanks-aquariums-and-nets",
      "aquariums",
      "clear-for-life"
    ]
  },
  {
    "sku": "amazon-pet-B09K4RLLSK",
    "tags": [
      "fish-accessory",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "hammocks",
      "liujaos",
      "asin-B09K4RLLSK"
    ]
  }
];

export default entries;