// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// One entry per category index file. Only includes products that have an image.

export interface CategoryIndex {
  /** Filename (relative to this folder), e.g. "dog-dry-food.ts" */
  filename: string;
  /** High-level tags describing the content of this file */
  tags: string[];
  /** Number of products in this file */
  count: number;
}

const indexes: CategoryIndex[] = [
  {
    "filename": "dog-dry-food.ts",
    "tags": [
      "dog",
      "food",
      "dry",
      "kibble"
    ],
    "count": 33
  },
  {
    "filename": "dog-wet-food.ts",
    "tags": [
      "dog",
      "food",
      "wet",
      "canned"
    ],
    "count": 21
  },
  {
    "filename": "dog-treat.ts",
    "tags": [
      "dog",
      "treat",
      "snack",
      "chew"
    ],
    "count": 19
  },
  {
    "filename": "dog-toy.ts",
    "tags": [
      "dog",
      "toy",
      "play"
    ],
    "count": 28
  },
  {
    "filename": "dog-accessory.ts",
    "tags": [
      "dog",
      "accessory",
      "collar",
      "leash",
      "bed",
      "bowl"
    ],
    "count": 139
  },
  {
    "filename": "dog-health.ts",
    "tags": [
      "dog",
      "health",
      "supplement",
      "medication",
      "veterinary"
    ],
    "count": 32
  },
  {
    "filename": "cat-dry-food.ts",
    "tags": [
      "cat",
      "food",
      "dry",
      "kibble"
    ],
    "count": 20
  },
  {
    "filename": "cat-wet-food.ts",
    "tags": [
      "cat",
      "food",
      "wet",
      "canned"
    ],
    "count": 28
  },
  {
    "filename": "cat-treat.ts",
    "tags": [
      "cat",
      "treat",
      "snack"
    ],
    "count": 10
  },
  {
    "filename": "cat-toy.ts",
    "tags": [
      "cat",
      "toy",
      "play",
      "wand"
    ],
    "count": 32
  },
  {
    "filename": "cat-accessory.ts",
    "tags": [
      "cat",
      "accessory",
      "litter",
      "collar",
      "bowl"
    ],
    "count": 56
  },
  {
    "filename": "cat-health.ts",
    "tags": [
      "cat",
      "health",
      "supplement",
      "medication",
      "veterinary"
    ],
    "count": 10
  },
  {
    "filename": "bird-food.ts",
    "tags": [
      "bird",
      "food",
      "treat",
      "seed"
    ],
    "count": 23
  },
  {
    "filename": "bird-toy.ts",
    "tags": [
      "bird",
      "toy",
      "perch",
      "swing"
    ],
    "count": 128
  },
  {
    "filename": "bird-accessory.ts",
    "tags": [
      "bird",
      "accessory",
      "cage",
      "nest",
      "perch"
    ],
    "count": 17
  },
  {
    "filename": "fish-food.ts",
    "tags": [
      "fish",
      "food",
      "flakes",
      "pellets"
    ],
    "count": 10
  },
  {
    "filename": "fish-accessory.ts",
    "tags": [
      "fish",
      "aquarium",
      "heater",
      "ornament",
      "accessory"
    ],
    "count": 38
  },
  {
    "filename": "small-pet-food.ts",
    "tags": [
      "small-pet",
      "rabbit",
      "hamster",
      "food",
      "treat"
    ],
    "count": 9
  },
  {
    "filename": "small-pet-toy.ts",
    "tags": [
      "small-pet",
      "toy",
      "play",
      "tunnel"
    ],
    "count": 9
  },
  {
    "filename": "small-pet-accessory.ts",
    "tags": [
      "small-pet",
      "accessory",
      "cage",
      "bed"
    ],
    "count": 20
  },
  {
    "filename": "farm-animal-food.ts",
    "tags": [
      "farm",
      "goat",
      "chicken",
      "livestock",
      "feed"
    ],
    "count": 9
  },
  {
    "filename": "pet-grooming.ts",
    "tags": [
      "grooming",
      "shampoo",
      "brush",
      "deodorizer"
    ],
    "count": 22
  },
  {
    "filename": "pet-health.ts",
    "tags": [
      "health",
      "supplement",
      "veterinary",
      "medication"
    ],
    "count": 2
  },
  {
    "filename": "other-pet.ts",
    "tags": [
      "pet",
      "accessory",
      "other"
    ],
    "count": 62
  }
];

export default indexes;