// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: other-pet  |  Products: 171

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-277091",
    "tags": [
      "other-pet",
      "pet-parents",
      "personalized-gifts",
      "coffee-mugs-tumblers",
      "frisco"
    ]
  },
  {
    "sku": "chewy-case of 16 — Friskies Lil’ Gravies Savory Salmon Flavor Cat Food Complement takes tastebuds to gravy purr-a-dise. Each pouch of this gravy-licious delight can be served as a topper for dry food or as a treat between meals.",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-case of 16 — Friskies Lil’ Gravies Roasted Chicken Flavor Cat Food Complement will satisfy gravy-loving cats everywhere. Each pouch of this gravy-licious delight can be used as a topper for crunchy dry cat food or as a treat between meals.",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-case of 16 — Make mealtimes memorable with Friskies Lil’ Gravies Roasted Turkey Flavor Cat Food Complement. Each pouch of this gravy-licious delight can be used as a topper for dry food or as a treat between meals.,InStock,,3.5,2,,,,,4e8b55cc-846a-5c3f-9268-b3f43c44db51,03/05/2023 21:37:26",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-326345",
    "tags": [
      "other-pet",
      "horse",
      "health-wellness",
      "first-aid",
      "cold-therapy",
      "ice-horse"
    ]
  },
  {
    "sku": "chewy-106386",
    "tags": [
      "other-pet",
      "horse",
      "grooming",
      "shampoos-conditioners",
      "shapley's"
    ]
  },
  {
    "sku": "chewy-304522",
    "tags": [
      "other-pet",
      "horse",
      "blankets",
      "fly-sheets-masks",
      "ear-nets",
      "horze-equestrian"
    ]
  },
  {
    "sku": "chewy-'https://chewy.wistia.com/embed/medias/n0fwfnb11b/swatch'",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-211224",
    "tags": [
      "other-pet",
      "horse",
      "health-wellness",
      "first-aid",
      "liniments-poultices",
      "ultracruz",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-135285",
    "tags": [
      "other-pet",
      "horse",
      "tack-saddlery",
      "halters-leads",
      "leads",
      "weaver-leather"
    ]
  },
  {
    "sku": "chewy-Quinoa",
    "tags": [
      "other-pet",
      "spinach"
    ]
  },
  {
    "sku": "chewy-Blueberry",
    "tags": [
      "other-pet",
      "dicalcium-phosphate"
    ]
  },
  {
    "sku": "chewy-Potassium Chloride",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Vitamins (Vitamin A Acetate",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Niacin",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Pyridoxine Hydrochloride",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Ferrous Sulfate",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Copper Sulfate",
    "tags": [
      "other-pet",
      "copper"
    ]
  },
  {
    "sku": "chewy-Calcium Iodate",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Dried Lactobacillus Acidophilus Fermentation",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Dried Bifido",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-89",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-90",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-Peppermint",
    "tags": [
      "other-pet",
      "green-tea-extract-3"
    ]
  },
  {
    "sku": "chewy-664710",
    "tags": [
      "other-pet",
      "horse",
      "riding-gear",
      "riding-apparel",
      "casual-riding-apparel",
      "shires-equestrian-products"
    ]
  },
  {
    "sku": "chewy-'https://image.chewy.com/is/image/catalog/277608_PT2._AC_SS500_V1619794376_.jpg'",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-you want to feed them food that will care for them right back. The Honest Kitchen Food Clusters Whole Grain Chicken & Oat Recipe Dehydrated Dog Food provides added nutrition and flavor to any mealtime. The clusters are made from cage-free chicken that’s been cold-pressed and dehydrated. This honest recipe is free of artificial flavors or preservatives",
    "tags": [
      "other-pet",
      "gums",
      "meaning-the-clusters-are-made-from-whole-foods-you’d-recognize-from-your-own-kitchen.,instock,['https://image.chewy.com/is/image/catalog/715630_main._ac_ss500_v1669734188_.jpg'",
      "has-ingredients",
      "has-calories"
    ]
  },
  {
    "sku": "chewy-165286",
    "tags": [
      "other-pet",
      "horse",
      "health-wellness",
      "first-aid",
      "hoof-care",
      "farnam",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-247580",
    "tags": [
      "other-pet",
      "horse",
      "tack-saddlery",
      "bridles-parts",
      "bridles",
      "weaver-leather"
    ]
  },
  {
    "sku": "chewy-Dried Whey",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "chewy-179372",
    "tags": [
      "other-pet",
      "reptile",
      "shop-by-reptile",
      "bearded-dragon",
      "heating-lighting",
      "zilla"
    ]
  },
  {
    "sku": "chewy-231575",
    "tags": [
      "other-pet",
      "horse",
      "tack-saddlery",
      "training",
      "whips-crops",
      "weaver-leather"
    ]
  },
  {
    "sku": "chewy-337614",
    "tags": [
      "other-pet",
      "horse",
      "blankets",
      "turnouts",
      "gatsby"
    ]
  },
  {
    "sku": "petsmart-5011233",
    "tags": [
      "other-pet",
      "small-pet",
      "starter-kits",
      "kaytee"
    ]
  },
  {
    "sku": "petsmart-5120589",
    "tags": [
      "other-pet",
      "reptile",
      "snake",
      "heating-and-lighting",
      "exo-terra"
    ]
  },
  {
    "sku": "petsmart-5290860",
    "tags": [
      "other-pet",
      "reptile",
      "feeders-and-food-storage",
      "feeding-accessories",
      "thrive-plastic-feeding-tongs-55871-html",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5152724",
    "tags": [
      "other-pet",
      "reptile",
      "cleaning-and-water-care",
      "sanitizers",
      "fluker's"
    ]
  },
  {
    "sku": "petsmart-5314443",
    "tags": [
      "other-pet",
      "reptile",
      "food",
      "cobalt"
    ]
  },
  {
    "sku": "petsmart-5291031",
    "tags": [
      "other-pet",
      "reptile",
      "substrate-and-bedding",
      "thrive-sphagnum-reptile-moss-54546-html",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5315110",
    "tags": [
      "other-pet",
      "reptile",
      "starter-kits",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5290927",
    "tags": [
      "other-pet",
      "reptile",
      "environmental-control-and-lighting",
      "bulbs-and-lamps",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5327958",
    "tags": [
      "other-pet",
      "small-pet",
      "food-treats-and-hay",
      "treats",
      "science-selective"
    ]
  },
  {
    "sku": "petsmart-5255515",
    "tags": [
      "other-pet",
      "reptile",
      "habitats-and-decor",
      "habitat-decor",
      "zoo-med"
    ]
  },
  {
    "sku": "petsmart-5300292",
    "tags": [
      "other-pet",
      "reptile",
      "feeders-and-food-storage",
      "feeding-accessories",
      "thrive-beardie-ball-59163-html",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5314812",
    "tags": [
      "other-pet",
      "reptile",
      "snake",
      "heating-and-lighting",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5314948",
    "tags": [
      "other-pet",
      "reptile",
      "snake",
      "decor-and-accessories",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5290974",
    "tags": [
      "other-pet",
      "reptile",
      "substrate-and-bedding",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5254790",
    "tags": [
      "other-pet",
      "reptile",
      "environmental-control-and-lighting",
      "light-fixtures",
      "zoo-med"
    ]
  },
  {
    "sku": "petsmart-5308927",
    "tags": [
      "other-pet",
      "small-pet",
      "food-treats-and-hay",
      "treats",
      "kaytee"
    ]
  },
  {
    "sku": "petsmart-5230037",
    "tags": [
      "other-pet",
      "reptile",
      "snake",
      "juvenile-fancy-ball-python-5230037-html",
      "null"
    ]
  },
  {
    "sku": "petsmart-2051087",
    "tags": [
      "other-pet",
      "featured-shops",
      "cyber-monday",
      "zoo-med"
    ]
  },
  {
    "sku": "petsmart-5315227",
    "tags": [
      "other-pet",
      "reptile",
      "starter-kits",
      "thrive"
    ]
  },
  {
    "sku": "petsmart-5282115",
    "tags": [
      "other-pet",
      "reptile",
      "substrate-and-bedding",
      "zoo-med"
    ]
  },
  {
    "sku": "petsmart-5238588",
    "tags": [
      "other-pet",
      "reptile",
      "lizard",
      "decor-and-accessories",
      "exo-terra"
    ]
  },
  {
    "sku": "petsmart-1051261",
    "tags": [
      "other-pet",
      "reptile",
      "food",
      "rep-cal"
    ]
  },
  {
    "sku": "petsmart-5312231",
    "tags": [
      "other-pet",
      "reptile",
      "food",
      "hikari"
    ]
  },
  {
    "sku": "petsmart-5290803",
    "tags": [
      "other-pet",
      "reptile",
      "snake",
      "decor-and-accessories",
      "thrive"
    ]
  },
  {
    "sku": "amazon-pet-B08NGKTL4B",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "habitat-d-cor",
      "pstardmoon",
      "asin-B08NGKTL4B"
    ]
  },
  {
    "sku": "amazon-pet-B096YG7VFH",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "food",
      "visit-the-nestor-store",
      "asin-B096YG7VFH"
    ]
  },
  {
    "sku": "amazon-pet-B07788TSJ9",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-boxes",
      "doskocil",
      "asin-B07788TSJ9"
    ]
  },
  {
    "sku": "amazon-pet-B09TTBJ6W5",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "macos",
      "asin-B09TTBJ6W5"
    ]
  },
  {
    "sku": "amazon-pet-B09C6KW5GR",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "feeding-watering-supplies",
      "bowls",
      "juyt",
      "asin-B09C6KW5GR"
    ]
  },
  {
    "sku": "amazon-pet-B00E1TBZP0",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "food",
      "zoo-med",
      "asin-B00E1TBZP0"
    ]
  },
  {
    "sku": "amazon-pet-B00EPJW9CO",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "beds",
      "red-dingo",
      "asin-B00EPJW9CO"
    ]
  },
  {
    "sku": "amazon-pet-B09C2H4WXV",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "toys",
      "belity",
      "asin-B09C2H4WXV"
    ]
  },
  {
    "sku": "amazon-pet-B000QSN08U",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "food",
      "kaytee",
      "asin-B000QSN08U"
    ]
  },
  {
    "sku": "amazon-pet-B001HZUD8Q",
    "tags": [
      "other-pet",
      "pet-supplies",
      "dogs",
      "carriers-travel-products",
      "carriers",
      "sherpa",
      "asin-B001HZUD8Q"
    ]
  },
  {
    "sku": "amazon-pet-B09GW4L44Q",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "beds-furniture",
      "scratching-pads",
      "qindao",
      "asin-B09GW4L44Q"
    ]
  },
  {
    "sku": "amazon-pet-B001BM3IPU",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "booda-products",
      "asin-B001BM3IPU"
    ]
  },
  {
    "sku": "amazon-pet-B09XBV5R1G",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "brawl-athletix",
      "asin-B09XBV5R1G"
    ]
  },
  {
    "sku": "amazon-pet-B09ZLGTDRL",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "litter-housebreaking",
      "litter-scoops",
      "vms-india",
      "asin-B09ZLGTDRL"
    ]
  },
  {
    "sku": "amazon-pet-B09WF3HGFS",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "food",
      "maalavya",
      "asin-B09WF3HGFS"
    ]
  },
  {
    "sku": "amazon-pet-B00XJKICA8",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "kaytee",
      "asin-B00XJKICA8"
    ]
  },
  {
    "sku": "amazon-pet-B09652FV3Q",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "food",
      "visit-the-nestor-store",
      "asin-B09652FV3Q"
    ]
  },
  {
    "sku": "amazon-pet-B09T3NM1ML",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "macos",
      "asin-B09T3NM1ML"
    ]
  },
  {
    "sku": "amazon-pet-B09M45BDBM",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "dogbit",
      "asin-B09M45BDBM"
    ]
  },
  {
    "sku": "amazon-pet-B0B217N5ZZ",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "health-supplies",
      "visit-the-anfotal-nutritions-store",
      "asin-B0B217N5ZZ"
    ]
  },
  {
    "sku": "amazon-pet-B07H6PWL74",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "carriers-strollers",
      "strollers",
      "petique",
      "asin-B07H6PWL74"
    ]
  },
  {
    "sku": "amazon-pet-B09Q948HVC",
    "tags": [
      "other-pet",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B09Q948HVC"
    ]
  },
  {
    "sku": "amazon-pet-B0B1D9ZSRQ",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "birdcage-accessories",
      "perches",
      "generic",
      "asin-B0B1D9ZSRQ"
    ]
  },
  {
    "sku": "amazon-pet-B09T6M7B18",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "macos",
      "asin-B09T6M7B18"
    ]
  },
  {
    "sku": "amazon-pet-B09TH12S2J",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "macos",
      "asin-B09TH12S2J"
    ]
  },
  {
    "sku": "amazon-pet-B0002ARF4C",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "food",
      "lafeber",
      "asin-B0002ARF4C"
    ]
  },
  {
    "sku": "amazon-pet-B001B160OC",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "food",
      "dr.-harvey's",
      "asin-B001B160OC"
    ]
  },
  {
    "sku": "amazon-pet-B07D351T4B",
    "tags": [
      "other-pet",
      "pet-supplies",
      "birds",
      "food",
      "vetafarm",
      "asin-B07D351T4B"
    ]
  },
  {
    "sku": "amazon-pet-B09TH5RSNC",
    "tags": [
      "other-pet",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "macos",
      "asin-B09TH5RSNC"
    ]
  },
  {
    "sku": "aliexpress-pet-00001",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00005",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00049",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00056",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00092",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00115",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00126",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00131",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00147",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00160",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00182",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00189",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00220",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00222",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00226",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00244",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00250",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00258",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00269",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00273",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00292",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00315",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00340",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00342",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00371",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00380",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00424",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00428",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00431",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00454",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00456",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00458",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00481",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00488",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00561",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00564",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00599",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00612",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00616",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00645",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00663",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00709",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00720",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00790",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00806",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00829",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00830",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00860",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00862",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00874",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00897",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00944",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00950",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00960",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-00980",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01006",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01046",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01070",
    "tags": [
      "other-pet"
    ]
  },
  {
    "sku": "aliexpress-pet-01079",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01085",
    "tags": [
      "other-pet",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01092",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01121",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01183",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01190",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01201",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01216",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01231",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01244",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01250",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01279",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01292",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01303",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01324",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01380",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01508",
    "tags": [
      "other-pet",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01569",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01647",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01712",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01714",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01800",
    "tags": [
      "other-pet",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01829",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01869",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01924",
    "tags": [
      "other-pet",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01974",
    "tags": [
      "other-pet",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01994",
    "tags": [
      "other-pet",
      "popular"
    ]
  }
];

export default entries;