// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: pet-health  |  Products: 12

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-277608",
    "tags": [
      "pet-health",
      "pharmacy",
      "horse-pharmacy",
      "dewormers-parasiticides",
      "zimecterin"
    ]
  },
  {
    "sku": "chewy-231996",
    "tags": [
      "pet-health",
      "horse",
      "health-wellness",
      "vitamins-supplements",
      "vitamins-minerals-overall-health",
      "uckele",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-196788",
    "tags": [
      "pet-health",
      "horse",
      "health-wellness",
      "vitamins-supplements",
      "digestive-care-probiotics",
      "formula-707",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "amazon-pet-B0B41YKR7V",
    "tags": [
      "pet-health",
      "pet-supplies",
      "birds",
      "food",
      "generic",
      "asin-B0B41YKR7V"
    ]
  },
  {
    "sku": "aliexpress-pet-00003",
    "tags": [
      "pet-health"
    ]
  },
  {
    "sku": "aliexpress-pet-00254",
    "tags": [
      "pet-health",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00613",
    "tags": [
      "pet-health"
    ]
  },
  {
    "sku": "aliexpress-pet-01139",
    "tags": [
      "pet-health"
    ]
  },
  {
    "sku": "aliexpress-pet-01230",
    "tags": [
      "pet-health",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01312",
    "tags": [
      "pet-health",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01834",
    "tags": [
      "pet-health"
    ]
  },
  {
    "sku": "aliexpress-pet-01841",
    "tags": [
      "pet-health",
      "popular",
      "best-seller",
      "in-stock"
    ]
  }
];

export default entries;