// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: pet-health  |  Products with image: 2 (2 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-196788",
    "tags": [
      "pet-health",
      "horse",
      "health-wellness",
      "vitamins-supplements",
      "digestive-care-probiotics",
      "formula-707",
      "has-ingredients",
      "has-nutrition"
    ]
  },
  {
    "sku": "amazon-pet-B0B41YKR7V",
    "tags": [
      "pet-health",
      "pet-supplies",
      "birds",
      "food",
      "generic",
      "asin-B0B41YKR7V"
    ]
  }
];

export default entries;