// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: pet-grooming  |  Products: 213

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "chewy-654102",
    "tags": [
      "pet-grooming",
      "cat",
      "grooming",
      "waterless-grooming",
      "deodorizing-sprays-colognes",
      "pet-md",
      "has-ingredients"
    ]
  },
  {
    "sku": "chewy-65494",
    "tags": [
      "pet-grooming",
      "cat",
      "litter-accessories",
      "litter-boxes",
      "litter-pans",
      "iris"
    ]
  },
  {
    "sku": "chewy-243543",
    "tags": [
      "pet-grooming",
      "dog",
      "grooming",
      "bath-shower-supplies",
      "bathtubs-shower-hose-accessories",
      "aquapaw"
    ]
  },
  {
    "sku": "chewy-124844",
    "tags": [
      "pet-grooming",
      "horse",
      "grooming",
      "brushes-combs",
      "decker-manufacturing-company"
    ]
  },
  {
    "sku": "chewy-141378",
    "tags": [
      "pet-grooming",
      "cat",
      "litter-accessories",
      "litter-boxes",
      "litter-pans",
      "frisco"
    ]
  },
  {
    "sku": "chewy-92315",
    "tags": [
      "pet-grooming",
      "dog",
      "cleaning-potty",
      "deodorizers-air-purifiers",
      "isle-of-dogs"
    ]
  },
  {
    "sku": "chewy-128191",
    "tags": [
      "pet-grooming",
      "cat",
      "grooming",
      "brushes-combs",
      "li'l-pals"
    ]
  },
  {
    "sku": "chewy-232951",
    "tags": [
      "pet-grooming",
      "dog",
      "grooming",
      "bath-shower-supplies",
      "dryers",
      "ez-groom"
    ]
  },
  {
    "sku": "chewy-345763",
    "tags": [
      "pet-grooming",
      "horse",
      "stable-supplies",
      "happy-horse"
    ]
  },
  {
    "sku": "petsmart-5284734",
    "tags": [
      "pet-grooming",
      "dog",
      "cleaning-supplies",
      "stain-and-odor-removers",
      "only-natural-pet"
    ]
  },
  {
    "sku": "petsmart-5307170",
    "tags": [
      "pet-grooming",
      "dog",
      "grooming-supplies",
      "shampoos-and-conditioners",
      "pet-head"
    ]
  },
  {
    "sku": "petsmart-5270934",
    "tags": [
      "pet-grooming",
      "dog",
      "grooming-supplies",
      "brushes-combs-and-blowdryers",
      "chi"
    ]
  },
  {
    "sku": "petsmart-5296480",
    "tags": [
      "pet-grooming",
      "cat",
      "grooming-supplies",
      "shampoos-and-conditioners",
      "whisker-city"
    ]
  },
  {
    "sku": "petsmart-5295652",
    "tags": [
      "pet-grooming",
      "dog",
      "grooming-supplies",
      "brushes-combs-and-blowdryers",
      "top-paw"
    ]
  },
  {
    "sku": "amazon-pet-B09P8RX26L",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "generic",
      "asin-B09P8RX26L"
    ]
  },
  {
    "sku": "amazon-pet-B09B98BDVB",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "claw-care",
      "ouee",
      "asin-B09B98BDVB"
    ]
  },
  {
    "sku": "amazon-pet-B00757W4KK",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "brushes",
      "hartz",
      "asin-B00757W4KK"
    ]
  },
  {
    "sku": "amazon-pet-B07D53MCQC",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "scissors",
      "smith-chu",
      "asin-B07D53MCQC"
    ]
  },
  {
    "sku": "amazon-pet-B082FB11N7",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "hair-removal-mitts-rollers",
      "visit-the-twiclo-store",
      "asin-B082FB11N7"
    ]
  },
  {
    "sku": "amazon-pet-B09312QG76",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "hair-removal-mitts-rollers",
      "vacu",
      "asin-B09312QG76"
    ]
  },
  {
    "sku": "amazon-pet-B09NGWKBN6",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "brushes",
      "topiky",
      "asin-B09NGWKBN6"
    ]
  },
  {
    "sku": "amazon-pet-B09YK5Y2F1",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "combs",
      "bizofft",
      "asin-B09YK5Y2F1"
    ]
  },
  {
    "sku": "amazon-pet-B09JKPHJQR",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "feeding-watering-supplies",
      "nursing-supplies",
      "pekdi",
      "asin-B09JKPHJQR"
    ]
  },
  {
    "sku": "amazon-pet-B09X3993RV",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "hair-removal-mitts-rollers",
      "generic",
      "asin-B09X3993RV"
    ]
  },
  {
    "sku": "amazon-pet-B094NQWWHN",
    "tags": [
      "pet-grooming",
      "pet-supplies",
      "cats",
      "grooming",
      "combs",
      "homgeel",
      "asin-B094NQWWHN"
    ]
  },
  {
    "sku": "aliexpress-pet-00009",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00015",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00022",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00024",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00043",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00054",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00059",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00062",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00065",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00070",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00081",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00088",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00090",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00091",
    "tags": [
      "pet-grooming",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00103",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00104",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00111",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00135",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00139",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00144",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00150",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00151",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00153",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00157",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00168",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00186",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00195",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00228",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00238",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00263",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00268",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00275",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00296",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00302",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00328",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00335",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00337",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00339",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00359",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00362",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00374",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00413",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00415",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00432",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00451",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00457",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00464",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00480",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00491",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00492",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00495",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00515",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00524",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00525",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00533",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00549",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00553",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00566",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00571",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00605",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00614",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00615",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00618",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00632",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00633",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00649",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00650",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00683",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00687",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00692",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00712",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00716",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00729",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00733",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00743",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00750",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00751",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00757",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00767",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00772",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00776",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00780",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00782",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00788",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00791",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00792",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00798",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00808",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00817",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00826",
    "tags": [
      "pet-grooming",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00840",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00855",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00858",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00878",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00923",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-00929",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-00947",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-00949",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-00976",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01004",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-01026",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01035",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01039",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01049",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01062",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01075",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01101",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-01120",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01136",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01146",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01155",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01164",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01165",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01200",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-01214",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01224",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01273",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01278",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01287",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01330",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01334",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01343",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01362",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01375",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01399",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01423",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01431",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01444",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01462",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01465",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01468",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01470",
    "tags": [
      "pet-grooming",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01478",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01482",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01499",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-01503",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01504",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01510",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01518",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01522",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01535",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01548",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01552",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01561",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01562",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01576",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01591",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01600",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01603",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01604",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01607",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01610",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01621",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01623",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01624",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01642",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01646",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01658",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-01664",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01667",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01689",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01699",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01707",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01724",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01742",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01743",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01765",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01787",
    "tags": [
      "pet-grooming"
    ]
  },
  {
    "sku": "aliexpress-pet-01796",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01799",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01802",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01815",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01822",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01825",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01828",
    "tags": [
      "pet-grooming",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01842",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01843",
    "tags": [
      "pet-grooming",
      "popular"
    ]
  },
  {
    "sku": "aliexpress-pet-01871",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01875",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01881",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01887",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller"
    ]
  },
  {
    "sku": "aliexpress-pet-01918",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01946",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01963",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01965",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01967",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01970",
    "tags": [
      "pet-grooming",
      "popular",
      "in-stock"
    ]
  },
  {
    "sku": "aliexpress-pet-01978",
    "tags": [
      "pet-grooming",
      "popular",
      "best-seller",
      "in-stock"
    ]
  }
];

export default entries;