// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: small-pet-food  |  Products with image: 9 (3 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "petsmart-5156307",
    "tags": [
      "small-pet-food",
      "small-pet",
      "food-treats-and-hay",
      "treats",
      "kaytee"
    ]
  },
  {
    "sku": "petsmart-5175719",
    "tags": [
      "small-pet-food",
      "small-pet",
      "food-treats-and-hay",
      "treats",
      "brown's"
    ]
  },
  {
    "sku": "petsmart-5291261",
    "tags": [
      "small-pet-food",
      "small-pet",
      "toys-and-habitat-accessories",
      "toys",
      "oxbow"
    ]
  },
  {
    "sku": "petsmart-5271454",
    "tags": [
      "small-pet-food",
      "small-pet",
      "food-treats-and-hay",
      "treats",
      "brown's"
    ]
  },
  {
    "sku": "amazon-pet-B0B63VR9V9",
    "tags": [
      "small-pet-food",
      "pet-supplies",
      "small-animals",
      "food",
      "aixing",
      "asin-B0B63VR9V9"
    ]
  },
  {
    "sku": "amazon-pet-B09HSBKV2F",
    "tags": [
      "small-pet-food",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "vms-india",
      "asin-B09HSBKV2F"
    ]
  },
  {
    "sku": "amazon-pet-B0B6W6T84Q",
    "tags": [
      "small-pet-food",
      "pet-supplies",
      "small-animals",
      "food",
      "generic",
      "asin-B0B6W6T84Q"
    ]
  },
  {
    "sku": "amazon-pet-B0B247RNN5",
    "tags": [
      "small-pet-food",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "loww",
      "asin-B0B247RNN5"
    ]
  },
  {
    "sku": "amazon-pet-B09KNKPKF1",
    "tags": [
      "small-pet-food",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "visit-the-lovely-pets-kingdom-–-your-pet-our-passion-store",
      "asin-B09KNKPKF1"
    ]
  }
];

export default entries;