// Auto-generated by compile-pets-products.ts — DO NOT EDIT MANUALLY
// Source: datasets4/pets/  |  Bucket: small-pet-accessory  |  Products with image: 20 (2 excluded — no image)

export interface IndexEntry {
  sku: string;
  tags: string[];
}

const entries: IndexEntry[] = [
  {
    "sku": "petsmart-5318804",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "cages-habitats-and-hutches",
      "tunnels-and-hideouts",
      "full-cheeks"
    ]
  },
  {
    "sku": "petsmart-5318341",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "litter-and-bedding",
      "full-cheeks"
    ]
  },
  {
    "sku": "petsmart-5278509",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "litter-and-bedding",
      "kaytee"
    ]
  },
  {
    "sku": "petsmart-5141661",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "live-small-pets",
      "hamsters-guinea-pigs-and-more",
      "fancy-bear-hamster-15343-html",
      "null"
    ]
  },
  {
    "sku": "petsmart-2051001",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "health-and-grooming",
      "vitamins-and-supplements",
      "kordon"
    ]
  },
  {
    "sku": "petsmart-5126273",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "cages-habitats-and-hutches",
      "hutches",
      "ware"
    ]
  },
  {
    "sku": "petsmart-5318524",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "toys-and-habitat-accessories",
      "toys",
      "full-cheeks"
    ]
  },
  {
    "sku": "petsmart-5331188",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "toys-and-habitat-accessories",
      "toys",
      "oxbow"
    ]
  },
  {
    "sku": "petsmart-5255966",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "litter-and-bedding",
      "carefresh"
    ]
  },
  {
    "sku": "petsmart-5175796",
    "tags": [
      "small-pet-accessory",
      "small-pet",
      "cages-habitats-and-hutches",
      "cages",
      "kaytee-rabbit-home-habitat-44847-html",
      "kaytee"
    ]
  },
  {
    "sku": "amazon-pet-B07HMTPRFX",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "health-supplies",
      "visit-the-iilio-store",
      "asin-B07HMTPRFX"
    ]
  },
  {
    "sku": "amazon-pet-B0002AS668",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "tubes-tunnels",
      "kaytee",
      "asin-B0002AS668"
    ]
  },
  {
    "sku": "amazon-pet-B0B6W5ZL4F",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "generic",
      "asin-B0B6W5ZL4F"
    ]
  },
  {
    "sku": "amazon-pet-B088VVPL18",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "cats",
      "toys",
      "mice-animal-toys",
      "pet-craft-supply",
      "asin-B088VVPL18"
    ]
  },
  {
    "sku": "amazon-pet-B07HCMHW3X",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "bedding-litter",
      "fdit",
      "asin-B07HCMHW3X"
    ]
  },
  {
    "sku": "amazon-pet-B010TMF4H2",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "cats",
      "collars-harnesses-leashes",
      "collars",
      "sandia-pet",
      "asin-B010TMF4H2"
    ]
  },
  {
    "sku": "amazon-pet-B09XKV3MXH",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "beds",
      "01-02-015",
      "asin-B09XKV3MXH"
    ]
  },
  {
    "sku": "amazon-pet-B09XTS4TT2",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "01-02-015",
      "asin-B09XTS4TT2"
    ]
  },
  {
    "sku": "amazon-pet-B0B187J8CK",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "beds",
      "generic",
      "asin-B0B187J8CK"
    ]
  },
  {
    "sku": "amazon-pet-B09FK1QRL5",
    "tags": [
      "small-pet-accessory",
      "pet-supplies",
      "small-animals",
      "houses-habitats",
      "cages",
      "ecomspace",
      "asin-B09FK1QRL5"
    ]
  }
];

export default entries;